import{getApps,getApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import{getFirestore,doc,getDoc}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const app=getApps().length?getApp():null;if(!app)throw new Error('Firebase não iniciado');const auth=getAuth(app),db=getFirestore(app);const OWNER_UID='0Mhnp79AYQTLwH6vfpAKROSGBtU2';let timer=null,busy=false;
async function adminAllowed(u){if(!u)return false;if(u.uid===OWNER_UID)return true;try{const s=await getDoc(doc(db,'users',u.uid));return s.exists()&&s.data().admin===true}catch{return false}}
function refreshMenu(){const menu=document.getElementById('chamaMobileMenu'),btn=document.getElementById('chamaMobileMenuBtn');if(menu?.classList.contains('open')&&btn){btn.click();setTimeout(()=>btn.click(),20)}}
function directButton(u){if(!u||document.getElementById('adminBtn'))return;const top=document.querySelector('.topbar');if(!top)return;const b=document.createElement('button');b.id='adminBtn';b.className='admin-btn';b.textContent='🛡️ Admin';b.type='button';b.onclick=async()=>{try{await import(`./admin-panel.js?adminopen=${Date.now()}`);setTimeout(()=>{const m=document.getElementById('adminModal');if(m)m.classList.remove('hidden');else alert('Painel Admin carregando. Toque novamente em Admin.')},300)}catch{alert('Não consegui abrir o painel Admin agora.')}};top.insertBefore(b,document.getElementById('logoutBtn')||null);refreshMenu()}
async function ensureAdmin(){if(busy)return;const u=auth.currentUser;if(!u||document.getElementById('adminBtn'))return;busy=true;try{if(!(await adminAllowed(u)))return;directButton(u);try{await import(`./admin-panel.js?recover=${Date.now()}`)}catch(e){console.warn('Admin recovery import:',e)}directButton(u)}finally{busy=false}}
function start(u){clearInterval(timer);if(!u)return;if(u.uid===OWNER_UID)directButton(u);ensureAdmin();setTimeout(ensureAdmin,150);setTimeout(ensureAdmin,700);setTimeout(ensureAdmin,1600);timer=setInterval(ensureAdmin,2000)}
onAuthStateChanged(auth,start);
new MutationObserver(()=>{const u=auth.currentUser;if(!u||document.getElementById('adminBtn'))return;if(u.uid===OWNER_UID)directButton(u);else setTimeout(ensureAdmin,40)}).observe(document.body,{childList:true,subtree:true});
document.addEventListener('click',e=>{if(!e.target.closest('#chamaMobileMenuBtn'))return;const u=auth.currentUser;if(u?.uid===OWNER_UID)directButton(u);setTimeout(ensureAdmin,10)},true);
