import{getApps,getApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import{getFirestore,doc,getDoc}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const app=getApps().length?getApp():null;if(!app)throw new Error('Firebase não iniciado');const auth=getAuth(app),db=getFirestore(app);const OWNER_UID='0Mhnp79AYQTLwH6vfpAKROSGBtU2';let timer=null,busy=false;
async function adminAllowed(u){if(!u)return false;if(u.uid===OWNER_UID)return true;try{const s=await getDoc(doc(db,'users',u.uid));return s.exists()&&s.data().admin===true}catch{return false}}
function refreshMenu(){const menu=document.getElementById('chamaMobileMenu'),btn=document.getElementById('chamaMobileMenuBtn');if(menu?.classList.contains('open')&&btn){btn.click();setTimeout(()=>btn.click(),20)}}
function fallback(u){if(!u||document.getElementById('adminBtn'))return;const top=document.querySelector('.topbar');if(!top)return;const b=document.createElement('button');b.id='adminBtn';b.dataset.recovery='1';b.className='admin-btn';b.textContent='🛡️ Admin';b.type='button';b.onclick=()=>openAdmin(u);top.insertBefore(b,document.getElementById('logoutBtn')||null);refreshMenu()}
async function openAdmin(u){if(!(await adminAllowed(u)))return alert('Sua conta não tem permissão de administrador.');document.querySelector('#adminBtn[data-recovery="1"]')?.remove();try{await import(`./admin-panel.js?recover=${Date.now()}`);await new Promise(r=>setTimeout(r,250));const real=document.querySelector('#adminBtn:not([data-recovery="1"])');if(real){real.click();return}const m=document.getElementById('adminModal');if(m){m.classList.remove('hidden');return}}catch(e){console.warn('Admin panel:',e)}fallback(u);alert('Não consegui abrir o painel Admin. Tente novamente em alguns segundos.')}
async function ensureAdmin(){if(busy)return;const u=auth.currentUser;if(!u)return;busy=true;try{if(!(await adminAllowed(u)))return;if(!document.getElementById('adminBtn')){try{await import(`./admin-panel.js?boot=${Date.now()}`);await new Promise(r=>setTimeout(r,180))}catch(e){console.warn('Admin boot:',e)}if(!document.getElementById('adminBtn'))fallback(u)}refreshMenu()}finally{busy=false}}
function start(u){clearInterval(timer);if(!u)return;ensureAdmin();setTimeout(ensureAdmin,300);setTimeout(ensureAdmin,1000);timer=setInterval(ensureAdmin,3000)}
onAuthStateChanged(auth,start);
new MutationObserver(()=>{if(auth.currentUser&&!document.getElementById('adminBtn'))setTimeout(ensureAdmin,80)}).observe(document.body,{childList:true,subtree:true});
document.addEventListener('click',e=>{if(e.target.closest('#chamaMobileMenuBtn'))setTimeout(ensureAdmin,20)},true);
