(()=>{
  if(!/(^|\/)admin(?:\.html)?\/?$/i.test(location.pathname))return;
  if(window.__chamaAdminStatusLoaded)return;window.__chamaAdminStatusLoaded=true;
  let db=null,fs=null,allowed=false;
  const STYLE_ID='chamaAdminStatusStyleV1';
  const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
  const safeUrl=v=>{try{const u=new URL(String(v||'').trim(),location.origin);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
  const msOf=v=>v?.toMillis?v.toMillis():typeof v==='number'?v:0;
  const fmt=v=>{const ms=msOf(v);if(!ms)return 'Data não disponível';return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(ms))};
  const age=v=>{const ms=msOf(v),d=Math.max(0,Date.now()-ms);if(d<60000)return'agora';if(d<3600000)return Math.floor(d/60000)+' min';if(d<86400000)return Math.floor(d/3600000)+' h';return Math.floor(d/86400000)+' d'};
  function styles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`.admin-status-card{border:1px solid #f0c86a!important;background:#fffdf7!important}.admin-status-head{display:flex;align-items:center;gap:10px}.admin-status-head h2{flex:1}.admin-status-badge{display:inline-flex;align-items:center;gap:6px;background:#fff0f0;color:#b42318;border-radius:999px;padding:6px 9px;font-size:11px;font-weight:900}.admin-status-help{font-size:13px;color:#68756e;line-height:1.45;margin:7px 0 12px}.admin-status-actions{display:flex;gap:8px;margin-bottom:10px}.admin-status-refresh{border:1px solid #cad5cf;background:#fff;color:#0b7a53;border-radius:11px;padding:9px 12px;font-weight:850}.admin-status-list{display:grid;gap:9px}.admin-status-row{border:1px solid #e3e8e5;border-radius:14px;padding:11px;background:#fff}.admin-status-row.expired{border-color:#f0b9b5;background:#fffafa}.admin-status-row-top{display:flex;align-items:center;gap:9px}.admin-status-avatar{width:38px;height:38px;border-radius:50%;background:#e7f5ee;color:#0b7a53;display:grid;place-items:center;font-weight:900;overflow:hidden;flex:0 0 38px}.admin-status-avatar img{width:100%;height:100%;object-fit:cover}.admin-status-main{flex:1;min-width:0}.admin-status-main strong{display:block}.admin-status-main small{display:block;color:#68756e;margin-top:2px}.admin-status-dot{width:9px;height:9px;border-radius:50%;background:#d92d20;display:inline-block;margin-right:5px}.admin-status-media{width:100%;max-height:160px;object-fit:contain;background:#111;border-radius:10px;margin-top:9px}.admin-status-delete{margin-top:9px;border:0;background:#fff0f0;color:#b42318;border-radius:10px;padding:9px 11px;font-weight:850;width:100%}.admin-status-delete:disabled{opacity:.6}.admin-status-empty{padding:14px 4px;color:#68756e;text-align:center}.admin-status-count{font-size:13px;color:#68756e;margin-bottom:8px}`;document.head.appendChild(s)}
  function ensureCard(){if(document.getElementById('adminStatusCard'))return document.getElementById('adminStatusCard');const panel=document.getElementById('panel');if(!panel)return null;const card=document.createElement('section');card.id='adminStatusCard';card.className='card admin-status-card';card.innerHTML='<div class="admin-status-head"><h2>🔴 Status para apagar</h2><span id="adminStatusBadge" class="admin-status-badge">0 expirados</span></div><div class="admin-status-help">Os Status continuam válidos por 24 horas. Depois desse prazo, eles aparecem aqui com um ponto vermelho. A contagem é calculada no navegador usando a data já salva no Status; não há consulta a cada minuto.</div><div class="admin-status-actions"><button id="adminStatusRefresh" class="admin-status-refresh" type="button">↻ Atualizar Status</button></div><div id="adminStatusCount" class="admin-status-count"></div><div id="adminStatusList" class="admin-status-list"></div>';panel.prepend(card);card.querySelector('#adminStatusRefresh').onclick=load;return card}
  function render(items){const card=ensureCard();if(!card)return;const list=card.querySelector('#adminStatusList'),badge=card.querySelector('#adminStatusBadge'),count=card.querySelector('#adminStatusCount');const now=Date.now();items.sort((a,b)=>msOf(b.createdAt)-msOf(a.createdAt));const expired=items.filter(x=>{const e=msOf(x.expiresAt);return e>0&&e<=now});badge.textContent=`${expired.length} expirado${expired.length===1?'':'s'}`;count.textContent=`${items.length} Status carregados · ${expired.length} prontos para apagar`;if(!expired.length){list.innerHTML='<div class="admin-status-empty">Nenhum Status passou de 24 horas. ✓</div>';return}list.innerHTML='';expired.forEach(x=>{const row=document.createElement('article');row.className='admin-status-row expired';const photo=safeUrl(x.photoUrl);const initial=esc((x.nome||'U').trim().charAt(0).toUpperCase());row.innerHTML=`<div class="admin-status-row-top"><div class="admin-status-avatar">${photo?`<img src="${esc(photo)}" alt="">`:initial}</div><div class="admin-status-main"><strong><span class="admin-status-dot"></span>${esc(x.nome||'Usuário')}</strong><small>Publicado: ${esc(fmt(x.createdAt))} · ${esc(age(x.createdAt))}</small><small>Expirou: ${esc(fmt(x.expiresAt))}</small></div></div>${x.text?`<div class="admin-status-help">${esc(x.text)}</div>`:''}${x.mediaUrl?`<${x.kind==='video'?'video':'img'} class="admin-status-media" src="${esc(safeUrl(x.mediaUrl))}" ${x.kind==='video'?'controls playsinline preload="metadata"':'loading="lazy"'}></${x.kind==='video'?'video':'img'}>`:''}<button class="admin-status-delete" type="button">🗑️ Apagar Status</button>`;row.querySelector('.admin-status-delete').onclick=()=>removeStatus(x,row);list.appendChild(row)});}
  async function load(){if(!allowed||!db||!fs)return;const list=document.getElementById('adminStatusList');if(list)list.innerHTML='<div class="admin-status-empty">Carregando Status...</div>';try{const snap=await fs.getDocs(fs.query(fs.collection(db,'statuses'),fs.limit(50)));const items=[];snap.forEach(d=>items.push({id:d.id,...(d.data()||{})}));render(items)}catch(e){console.error('[Chama Admin Status]',e);if(list)list.innerHTML='<div class="admin-status-empty">Não foi possível carregar os Status agora.</div>'}}
  async function removeStatus(x,row){if(!allowed||!x?.id)return;const btn=row?.querySelector('.admin-status-delete');if(btn){btn.disabled=true;btn.textContent='Apagando...'}try{await fs.deleteDoc(fs.doc(db,'statuses',x.id));row.remove();const badge=document.getElementById('adminStatusBadge');const count=document.getElementById('adminStatusCount');const n=Math.max(0,(Number((badge?.textContent||'0').match(/\d+/)?.[0])||0)-1);if(badge)badge.textContent=`${n} expirado${n===1?'':'s'}`;if(count)count.textContent='Status atualizado após a exclusão.'}catch(e){console.error('[Chama Admin Status]',e);alert('Não foi possível apagar este Status agora.');if(btn){btn.disabled=false;btn.textContent='🗑️ Apagar Status'}}}
  async function start(){styles();ensureCard();try{const appMod=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js');let app=appMod.getApps()[0];for(let i=0;!app&&i<20;i++){await new Promise(r=>setTimeout(r,100));app=appMod.getApps()[0]}if(!app)return;const [a,f]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js')]);fs=f;db=f.getFirestore(app);const auth=a.getAuth(app);a.onAuthStateChanged(auth,async user=>{allowed=false;if(!user)return;try{const s=await f.getDoc(f.doc(db,'users',user.uid));allowed=s.exists()&&s.data().admin===true;if(allowed)load()}catch(e){console.warn('[Chama Admin Status]',e)}})}catch(e){console.warn('[Chama Admin Status] módulo não iniciou',e)}}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();
})();
