(()=>{
  const STYLE='chamaAvatarV3Style', cache=new Map(), pending=new Map();
  const $=id=>document.getElementById(id);
  const safe=v=>{try{const u=new URL(String(v||''),location.origin);return u.origin===location.origin&&u.pathname==='/api/media'&&u.searchParams.get('key')?u.href:''}catch{return ''}};
  function style(){if($(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent='#chatAvatar{overflow:hidden}#chatAvatar img,.chama-v3-avatar img{width:100%;height:100%;object-fit:cover;display:block}.chama-v3-avatar{width:44px;height:44px;border-radius:50%;overflow:hidden;display:grid;place-items:center;background:#dff4ea;color:#0b7a53;font-weight:800;flex:0 0 44px}';document.head.appendChild(s)}
  async function fb(){const [a,f]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js')]);const app=a.getApps()[0];if(!app)throw 0;return{db:f.getFirestore(app),doc:f.doc,getDoc:f.getDoc,getDocs:f.getDocs,collection:f.collection,query:f.query,where:f.where,limit:f.limit}}
  async function uidByEmail(email){email=String(email||'').trim().toLowerCase();if(!email)return '';if(cache.has('uid:'+email))return cache.get('uid:'+email);if(pending.has('uid:'+email))return pending.get('uid:'+email);const p=(async()=>{try{const x=await fb(),q=x.query(x.collection(x.db,'users'),x.where('email','==',email),x.limit(1)),s=await x.getDocs(q);const uid=s.empty?'':s.docs[0].id;cache.set('uid:'+email,uid);return uid}catch(e){console.warn('avatar uid',e);return ''}})();pending.set('uid:'+email,p);const r=await p;pending.delete('uid:'+email);return r}
  async function photo(uid){if(!uid)return '';if(cache.has('p:'+uid))return cache.get('p:'+uid);if(pending.has('p:'+uid))return pending.get('p:'+uid);const p=(async()=>{try{const x=await fb(),s=await x.getDoc(x.doc(x.db,'publicProfiles',uid)),u=s.exists()?safe(s.data()?.photoUrl):'';cache.set('p:'+uid,u);return u}catch(e){console.warn('avatar photo',e);return ''}})();pending.set('p:'+uid,p);const r=await p;pending.delete('p:'+uid);return r}
  function render(el,url,name){if(!el)return;el.innerHTML='';const u=safe(url),letter=(String(name||'U').trim()[0]||'U').toUpperCase();if(!u){el.textContent=letter;return}const img=document.createElement('img');img.alt='Foto de perfil';img.src=u;img.onerror=()=>{el.textContent=letter};el.appendChild(img)}
  async function row(row){const av=row.querySelector('.avatar');if(!av)return;const email=row.querySelector('.user-email')?.textContent||'';const uid=await uidByEmail(email);if(uid){row.dataset.uid=uid;render(av,await photo(uid),row.querySelector('.user-name')?.textContent)}}
  async function chat(){const av=$('chatAvatar'),email=$('chatEmail')?.textContent||'';if(!av||!email)return;const uid=await uidByEmail(email);if(uid)render(av,await photo(uid),$('chatName')?.textContent)}
  async function scan(){for(const r of document.querySelectorAll('#usersList .user'))row(r);chat()}
  function start(){style();setTimeout(scan,800);new MutationObserver(()=>scan()).observe(document.body,{childList:true,subtree:true});setInterval(scan,4000)}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();
})();