import{getApps,getApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getFirestore,doc,getDoc}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const app=getApps().length?getApp():null;if(!app)throw new Error('Firebase não iniciado');const db=getFirestore(app);
const BASE='https://chama.alibr.com.br/';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const safe=v=>{try{const u=new URL(String(v||''));return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
function style(){if(document.getElementById('ccStyle'))return;const s=document.createElement('style');s.id='ccStyle';s.textContent=`.cc-share{width:min(300px,76vw);background:#fff;border:1px solid #dbe7e1;border-radius:15px;overflow:hidden}.cc-cover{height:116px;background:#eef4f1;display:grid;grid-template-columns:repeat(3,1fr);gap:2px;overflow:hidden}.cc-cover img{width:100%;height:100%;object-fit:cover}.cc-cover .cc-ph{display:grid;place-items:center;font-size:26px;background:#e5f3ec}.cc-share-body{padding:10px}.cc-share-title{font-weight:850;color:#173f33;font-size:15px}.cc-share-sub{font-size:12px;color:#718078;margin-top:3px}.cc-open{width:100%;border:0;background:#0b7a53;color:#fff;padding:10px;border-radius:10px;margin-top:8px;font-weight:850}.cc-modal{position:fixed;inset:0;background:#0009;z-index:980;display:flex;align-items:flex-end;justify-content:center}.cc-shop{width:min(650px,100%);height:min(90dvh,760px);background:#f5f7f6;border-radius:22px 22px 0 0;display:flex;flex-direction:column;overflow:hidden}.cc-head{background:#fff;padding:14px 16px;display:flex;align-items:center;gap:10px;border-bottom:1px solid #e4ebe7}.cc-head-main{flex:1;min-width:0}.cc-head-title{font-size:19px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cc-head-sub{font-size:12px;color:#718078;margin-top:2px}.cc-close{border:0;background:#eaf3ef;color:#0b7a53;width:40px;height:40px;border-radius:50%;font-size:24px}.cc-scroll{flex:1;overflow:auto;padding:10px}.cc-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.cc-product{background:#fff;border:1px solid #e0e7e3;border-radius:14px;overflow:hidden;min-width:0}.cc-img{aspect-ratio:1/1;background:#edf2ef;overflow:hidden;display:grid;place-items:center;color:#718078;font-size:12px}.cc-img img{width:100%;height:100%;object-fit:cover}.cc-body{padding:9px}.cc-p-title{font-size:13px;font-weight:800;line-height:1.25;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;min-height:33px}.cc-price{font-weight:900;color:#0b7a53;margin:6px 0}.cc-platform{font-size:10px;color:#7b8781;text-transform:uppercase}.cc-actions{display:grid;gap:6px}.cc-view,.cc-ask{display:block;text-align:center;text-decoration:none;border:0;border-radius:9px;padding:8px;font-size:12px;font-weight:850}.cc-view{background:#0b7a53;color:#fff}.cc-ask{background:#e9f5ef;color:#0b7a53}.cc-more{padding:14px;text-align:center;color:#718078;font-size:12px}@media(max-width:420px){.cc-scroll{padding:8px}.cc-grid{gap:8px}.cc-body{padding:8px}}`;document.head.appendChild(s)}
function getUid(text){const m=String(text||'').match(/[?&]catalogo=([^\s&#]+)/i);if(!m)return'';try{return decodeURIComponent(m[1])}catch{return m[1]}}
async function loadProfile(uid){const s=await getDoc(doc(db,'publicProfiles',uid));return s.exists()?s.data():null}
function askAbout(p,uid,i){document.querySelector('.cc-modal')?.remove();const input=document.getElementById('messageInput');if(!input)return;const link=`${BASE}?produto=${encodeURIComponent(uid+':'+i)}`;input.value=`Quero saber sobre este produto: ${p.titulo||'Produto'}\n${link}`;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()}
async function openShop(uid){document.querySelector('.cc-modal')?.remove();const modal=document.createElement('div');modal.className='cc-modal';modal.innerHTML='<section class="cc-shop"><div class="cc-head"><div class="cc-head-main"><div class="cc-head-title">Catálogo</div><div class="cc-head-sub">Carregando...</div></div><button class="cc-close">×</button></div><div class="cc-scroll"><div class="cc-grid"></div><div class="cc-more">Carregando produtos...</div></div></section>';document.body.appendChild(modal);modal.querySelector('.cc-close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};try{const p=await loadProfile(uid);if(!p)throw new Error();const items=Array.isArray(p.catalogo)?p.catalogo:[];modal.querySelector('.cc-head-title').textContent=`Catálogo de ${p.nome||'usuário'}`;modal.querySelector('.cc-head-sub').textContent=`${items.length} produto${items.length===1?'':'s'} • role para ver mais`;const grid=modal.querySelector('.cc-grid'),more=modal.querySelector('.cc-more');let shown=0;function renderNext(){const end=Math.min(shown+8,items.length);for(let i=shown;i<end;i++){const x=items[i],img=safe(x.imagem),link=safe(x.link),card=document.createElement('article');card.className='cc-product';card.innerHTML=`<div class="cc-img">${img?`<img loading="lazy" src="${esc(img)}" alt="${esc(x.titulo||'Produto')}">`:'Sem imagem'}</div><div class="cc-body"><div class="cc-platform">${esc(x.plataforma||'Produto')}</div><div class="cc-p-title">${esc(x.titulo||'Produto')}</div>${x.preco?`<div class="cc-price">${esc(x.preco)}</div>`:''}<div class="cc-actions">${link?`<a class="cc-view" href="${esc(link)}" target="_blank" rel="noopener sponsored">Ver produto</a>`:''}<button class="cc-ask" type="button">💬 Perguntar</button></div></div>`;card.querySelector('.cc-ask').onclick=()=>askAbout(x,uid,i);grid.appendChild(card)}shown=end;more.textContent=shown<items.length?'Role para carregar mais':'Fim do catálogo'}renderNext();const scroll=modal.querySelector('.cc-scroll');scroll.addEventListener('scroll',()=>{if(shown<items.length&&scroll.scrollTop+scroll.clientHeight>=scroll.scrollHeight-220)renderNext()},{passive:true})}catch{modal.querySelector('.cc-head-sub').textContent='Não foi possível carregar este catálogo.';modal.querySelector('.cc-more').textContent='Tente novamente mais tarde.'}}
async function renderBubble(b){if(b.dataset.ccDone)return;const raw=(b.textContent||'').trim(),uid=getUid(raw);if(!uid)return;b.dataset.ccDone='1';let p=null;try{p=await loadProfile(uid)}catch{};const items=Array.isArray(p?.catalogo)?p.catalogo:[],imgs=items.slice(0,3).map(x=>safe(x.imagem)).filter(Boolean);b.innerHTML=`<div class="cc-share"><div class="cc-cover">${[0,1,2].map(i=>imgs[i]?`<img loading="lazy" src="${esc(imgs[i])}" alt="Produto">`:'<div class="cc-ph">🛍️</div>').join('')}</div><div class="cc-share-body"><div class="cc-share-title">🛍️ Catálogo de ${esc(p?.nome||'usuário')}</div><div class="cc-share-sub">${items.length?items.length+' produtos para explorar':'Abra a vitrine completa'}</div><button class="cc-open" type="button">Ver catálogo</button></div></div>`;b.querySelector('.cc-open').onclick=()=>openShop(uid)}
function scan(){document.querySelectorAll('#messages .bubble').forEach(renderBubble)}
style();new MutationObserver(()=>{clearTimeout(window.__ccT);window.__ccT=setTimeout(scan,70)}).observe(document.body,{childList:true,subtree:true});document.addEventListener('click',()=>setTimeout(scan,80),true);scan();
