(()=>{
  const STYLE_ID='chamaSupportStyleV2',DEFAULTS={welcome:'Olá! Eu sou o atendimento do Chama. Como posso ajudar?',fallback:'Recebi sua dúvida. Nossa equipe poderá responder por aqui.',items:[]};
  let db=null,fs=null,me=null,config=DEFAULTS,stopMessages=null;
  const norm=v=>String(v||'').trim().toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ');
  function addStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
    .chama-support-entry{margin:10px 12px;border:1px solid #cfe8db;background:#eef8f3;border-radius:15px;padding:12px;display:flex;align-items:center;gap:11px;cursor:pointer}.chama-support-entry:active{background:#dff3e9}.chama-support-avatar{width:44px;height:44px;border-radius:50%;background:#0b7a53;color:#fff;display:grid;place-items:center;font-size:22px;flex:0 0 44px}.chama-support-entry b{display:block;color:#16372a}.chama-support-entry small{color:#607069}.chama-support-badge{margin-left:auto;background:#d92d20;color:#fff;border-radius:999px;min-width:22px;height:22px;padding:0 6px;display:grid;place-items:center;font-size:11px;font-weight:900}.chama-support-badge:empty{display:none}
    .chama-support-backdrop{position:fixed;inset:0;background:#0008;z-index:4200;display:grid;place-items:center;padding:12px}.chama-support-modal{width:min(520px,100%);height:min(720px,92dvh);background:#eef2ef;border-radius:22px;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 22px 65px #0005}.chama-support-head{background:#0b7a53;color:#fff;padding:13px 15px;display:flex;align-items:center;gap:10px}.chama-support-head-avatar{width:43px;height:43px;border-radius:50%;background:#ffffff22;display:grid;place-items:center;font-size:22px}.chama-support-head-main{flex:1}.chama-support-head-main b,.chama-support-head-main small{display:block}.chama-support-head-main small{opacity:.85}.chama-support-close{border:0;background:#ffffff20;color:#fff;width:39px;height:39px;border-radius:11px;font-size:19px}.chama-support-messages{flex:1;overflow:auto;padding:15px;display:flex;flex-direction:column;gap:9px}.chama-support-bubble{max-width:86%;padding:10px 12px;border-radius:15px;line-height:1.4;white-space:pre-wrap;overflow-wrap:anywhere}.chama-support-bot,.chama-support-admin{align-self:flex-start;background:#fff;border-bottom-left-radius:5px}.chama-support-admin{border-left:4px solid #0b7a53}.chama-support-user{align-self:flex-end;background:#d7f7e7;border-bottom-right-radius:5px}.chama-support-who{display:block;font-size:10px;font-weight:900;color:#0b7a53;margin-bottom:3px}.chama-support-suggestions{display:flex;gap:7px;overflow:auto;padding:0 12px 9px}.chama-support-suggestion{border:1px solid #bcdccb;background:#fff;color:#0b7a53;border-radius:999px;padding:8px 11px;white-space:nowrap;font-size:12px;font-weight:800}.chama-support-form{background:#fff;border-top:1px solid #dfe6e2;padding:10px;display:flex;gap:8px}.chama-support-form input{flex:1;min-width:0;border:1px solid #ccd7d1;border-radius:999px;padding:11px 14px;outline:none}.chama-support-send{border:0;background:#0b7a53;color:#fff;border-radius:50%;width:43px;height:43px;font-size:18px;flex:0 0 43px}
  `;document.head.appendChild(s)}
  function cleanConfig(d={}){const items=(Array.isArray(d.items)?d.items:[]).slice(0,20).map(x=>({question:String(x.question||'').trim().slice(0,120),keywords:String(x.keywords||'').trim().slice(0,240),answer:String(x.answer||'').trim().slice(0,1200)})).filter(x=>x.question&&x.answer);return {welcome:String(d.welcome||DEFAULTS.welcome).trim().slice(0,600)||DEFAULTS.welcome,fallback:String(d.fallback||DEFAULTS.fallback).trim().slice(0,600)||DEFAULTS.fallback,items}}
  function answerFor(text){const input=norm(text),words=new Set(input.split(' ').filter(x=>x.length>2));let best=null,score=0;for(const item of config.items){const terms=norm(item.keywords||item.question).split(' ').filter(x=>x.length>2);let n=0;for(const term of terms)if(input.includes(term)||words.has(term))n++;if(n>score){score=n;best=item}}return score?best?.answer||'':config.fallback}
  function close(){stopMessages?.();stopMessages=null;document.getElementById('chamaSupportModal')?.remove()}
  function renderMessages(box,snap){box.innerHTML='';if(snap.empty){const b=document.createElement('div');b.className='chama-support-bubble chama-support-bot';b.textContent=config.welcome;box.appendChild(b)}snap.forEach(d=>{const m=d.data()||{},b=document.createElement('div'),role=m.senderRole||'user';b.className='chama-support-bubble '+(role==='user'?'chama-support-user':role==='admin'?'chama-support-admin':'chama-support-bot');if(role!=='user'){const who=document.createElement('span');who.className='chama-support-who';who.textContent=role==='admin'?'Equipe do Chama':'Resposta automática';b.appendChild(who)}b.append(document.createTextNode(String(m.text||'')));box.appendChild(b)});box.scrollTop=box.scrollHeight}
  async function sendSupport(text){const ref=fs.doc(db,'supportChats',me.uid),messages=fs.collection(db,'supportChats',me.uid,'messages');await fs.setDoc(ref,{userId:me.uid,userName:me.displayName||me.email?.split('@')[0]||'Usuário',userEmail:me.email||'',lastMessage:text,updatedAt:fs.serverTimestamp(),unreadByAdmin:fs.increment(1)},{merge:true});await fs.addDoc(messages,{text,senderId:me.uid,senderRole:'user',createdAt:fs.serverTimestamp()});const auto=answerFor(text);if(auto)await fs.addDoc(messages,{text:auto,senderId:me.uid,senderRole:'bot',createdAt:fs.serverTimestamp()})}
  async function open(){if(!me)return alert('Faça login para falar com o Chama.');close();const back=document.createElement('div');back.id='chamaSupportModal';back.className='chama-support-backdrop';back.innerHTML=`<section class="chama-support-modal" role="dialog" aria-modal="true" aria-label="Fale com o Chama"><header class="chama-support-head"><div class="chama-support-head-avatar">🔥</div><div class="chama-support-head-main"><b>Fale com o Chama</b><small>Resposta automática e atendimento da equipe</small></div><button class="chama-support-close" type="button">✕</button></header><div class="chama-support-messages"></div><div class="chama-support-suggestions"></div><form class="chama-support-form"><input maxlength="500" placeholder="Digite sua dúvida..." autocomplete="off"><button class="chama-support-send" type="submit">➤</button></form></section>`;document.body.appendChild(back);back.querySelector('.chama-support-close').onclick=close;back.onclick=e=>{if(e.target===back)close()};const box=back.querySelector('.chama-support-messages'),input=back.querySelector('input'),send=back.querySelector('.chama-support-send'),suggestions=back.querySelector('.chama-support-suggestions');for(const item of config.items.slice(0,6)){const b=document.createElement('button');b.type='button';b.className='chama-support-suggestion';b.textContent=item.question;b.onclick=()=>submit(item.question);suggestions.appendChild(b)}const q=fs.query(fs.collection(db,'supportChats',me.uid,'messages'),fs.orderBy('createdAt','asc'),fs.limit(200));stopMessages=fs.onSnapshot(q,s=>renderMessages(box,s),()=>{box.innerHTML='<div class="chama-support-bubble chama-support-bot">Não foi possível carregar o atendimento agora.</div>'});await fs.updateDoc(fs.doc(db,'supportChats',me.uid),{unreadByUser:0}).catch(()=>{});async function submit(raw){const text=String(raw||'').trim();if(!text)return;input.value='';send.disabled=true;try{await sendSupport(text)}catch(e){console.error(e);alert('Não foi possível enviar sua dúvida agora.')}finally{send.disabled=false;input.focus()}}back.querySelector('form').onsubmit=e=>{e.preventDefault();submit(input.value)};setTimeout(()=>input.focus(),80)}
  function install(){const sidebar=document.querySelector('.sidebar');if(!sidebar||document.getElementById('chamaSupportEntry'))return;const entry=document.createElement('button');entry.id='chamaSupportEntry';entry.type='button';entry.className='chama-support-entry';entry.innerHTML='<span class="chama-support-avatar">🔥</span><span><b>Fale com o Chama</b><small>Tire suas dúvidas</small></span><span class="chama-support-badge"></span>';entry.onclick=open;const meBox=sidebar.querySelector('.me');if(meBox)meBox.insertAdjacentElement('afterend',entry);else sidebar.prepend(entry)}
  function watchUnread(){if(!me||!fs||!db)return;fs.onSnapshot(fs.doc(db,'supportChats',me.uid),s=>{const n=Math.max(0,Number(s.data()?.unreadByUser||0)),value=n?String(Math.min(n,99)):'';document.querySelectorAll('.chama-support-badge,.chama-support-quick-badge').forEach(b=>b.textContent=value)},()=>{})}
  async function init(){try{const appMod=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js');let app=appMod.getApps()[0];for(let i=0;!app&&i<25;i++){await new Promise(r=>setTimeout(r,100));app=appMod.getApps()[0]}if(!app)return;const [authMod,firestoreMod]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js')]);fs=firestoreMod;db=fs.getFirestore(app);const auth=authMod.getAuth(app);authMod.onAuthStateChanged(auth,async u=>{me=u||null;if(!u){config=DEFAULTS;return}try{const snap=await fs.getDoc(fs.doc(db,'appConfig','chamaSupport'));config=cleanConfig(snap.exists()?snap.data()||{}:{})}catch{config=DEFAULTS}watchUnread()})}catch(e){console.warn('Chama: suporte não iniciou',e)}}
  function start(){addStyle();install();init();document.addEventListener('chama-open-support',open);new MutationObserver(install).observe(document.body,{childList:true,subtree:true})}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();
})();
