import{getApps,getApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import{getFirestore,collection,doc,addDoc,updateDoc,getDoc,getDocs,query,orderBy,limit,arrayUnion,arrayRemove,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const app=getApps().length?getApp():null;
if(app){
 const auth=getAuth(app),db=getFirestore(app);let me=null,openedFromUrl=false;
 const css=`#channelsBtn{margin-right:6px}.ch-modal{position:fixed;inset:0;background:#0008;z-index:650;display:flex;align-items:flex-end;justify-content:center}.ch-card{width:min(680px,100%);max-height:88vh;overflow:auto;background:#fff;border-radius:20px 20px 0 0;padding:16px;font-family:Arial,sans-serif;color:#1f2d27}.ch-head{display:flex;gap:10px;align-items:center;position:sticky;top:-16px;background:#fff;padding:10px 0;z-index:2}.ch-head h3{margin:0;flex:1}.ch-x,.ch-btn{border:0;border-radius:10px;padding:10px 12px;font-weight:700}.ch-x{background:#eef3f0}.ch-btn{background:#0b7a53;color:#fff}.ch-btn.alt{background:#eef3f0;color:#174b38}.ch-list{display:grid;gap:10px}.ch-item{border:1px solid #dfe9e4;border-radius:14px;padding:12px;display:flex;gap:10px;align-items:center}.ch-avatar{width:48px;height:48px;border-radius:50%;object-fit:cover;background:#e7f0eb;display:grid;place-items:center;font-size:22px;overflow:hidden}.ch-main{flex:1;min-width:0}.ch-name{font-weight:800}.ch-desc{font-size:13px;color:#66756e;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ch-form{display:grid;gap:9px;margin:10px 0}.ch-form input,.ch-form textarea{width:100%;box-sizing:border-box;border:1px solid #ccd8d2;border-radius:10px;padding:11px;font:inherit}.ch-post{border-bottom:1px solid #e7ece9;padding:12px 0}.ch-post img{max-width:100%;border-radius:12px;margin-top:8px}.ch-meta{font-size:12px;color:#718078;margin-top:5px}`;
 const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
 function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function close(){document.querySelector('.ch-modal')?.remove()}
 function shell(title){close();const m=document.createElement('div');m.className='ch-modal';m.innerHTML=`<div class="ch-card"><div class="ch-head"><h3>${esc(title)}</h3><button class="ch-x">Fechar</button></div><div class="ch-body"></div></div>`;document.body.appendChild(m);m.querySelector('.ch-x').onclick=close;m.onclick=e=>{if(e.target===m)close()};return m.querySelector('.ch-body')}
 function ensureButton(){if(document.getElementById('channelsBtn'))return;const logout=document.getElementById('logoutBtn');if(!logout)return;const b=document.createElement('button');b.id='channelsBtn';b.className='iconbtn';b.type='button';b.textContent='📢 Canais';b.onclick=openChannels;logout.parentNode.insertBefore(b,logout)}
 async function openChannels(){const body=shell('Canais');body.innerHTML=`<div style="display:flex;gap:8px;margin-bottom:12px"><button id="chCreate" class="ch-btn">+ Criar canal</button><button id="chRefresh" class="ch-btn alt">Atualizar</button></div><div id="chList" class="ch-list">Carregando...</div>`;body.querySelector('#chCreate').onclick=createChannel;body.querySelector('#chRefresh').onclick=()=>loadChannels(body.querySelector('#chList'));await loadChannels(body.querySelector('#chList'))}
 async function loadChannels(box){try{const s=await getDocs(query(collection(db,'channels'),orderBy('createdAt','desc'),limit(100)));if(s.empty){box.innerHTML='<div>Nenhum canal criado ainda.</div>';return}box.innerHTML='';s.forEach(d=>{const c=d.data(),following=Array.isArray(c.followers)&&c.followers.includes(me?.uid),own=c.ownerId===me?.uid;const el=document.createElement('div');el.className='ch-item';el.innerHTML=`<div class="ch-avatar">${c.photo?`<img src="${esc(c.photo)}" style="width:100%;height:100%;object-fit:cover">`:'📢'}</div><div class="ch-main"><div class="ch-name">${esc(c.name||'Canal')}</div><div class="ch-desc">${esc(c.description||'')} · ${(c.followers||[]).length} seguidores</div></div><button class="ch-btn alt">${own?'Abrir':following?'Seguindo':'Ver'}</button>`;el.querySelector('button').onclick=()=>openChannel(d.id);box.appendChild(el)})}catch(e){console.warn(e);box.innerHTML='<div>Não foi possível carregar os canais.</div>'}}
 function createChannel(){const body=shell('Criar canal');body.innerHTML=`<div class="ch-form"><input id="cn" maxlength="60" placeholder="Nome do canal"><input id="cp" placeholder="Link da foto (opcional)"><textarea id="cd" maxlength="220" rows="3" placeholder="Descrição"></textarea><button id="cs" class="ch-btn">Criar canal</button></div>`;body.querySelector('#cs').onclick=async()=>{const name=body.querySelector('#cn').value.trim(),photo=body.querySelector('#cp').value.trim(),description=body.querySelector('#cd').value.trim();if(name.length<3)return alert('Digite um nome com pelo menos 3 letras.');const b=body.querySelector('#cs');b.disabled=true;b.textContent='Criando...';try{const ref=await addDoc(collection(db,'channels'),{name,photo,description,ownerId:me.uid,followers:[me.uid],createdAt:serverTimestamp(),updatedAt:serverTimestamp()});openChannel(ref.id)}catch(e){console.warn(e);alert('Não foi possível criar o canal.');b.disabled=false;b.textContent='Criar canal'}}}
 async function openChannel(id){const body=shell('Canal');body.innerHTML='Carregando...';try{const ref=doc(db,'channels',id),snap=await getDoc(ref);if(!snap.exists()){body.innerHTML='Canal não encontrado.';return}const c=snap.data(),own=c.ownerId===me.uid,following=Array.isArray(c.followers)&&c.followers.includes(me.uid);body.innerHTML=`<div class="ch-item"><div class="ch-avatar">${c.photo?`<img src="${esc(c.photo)}" style="width:100%;height:100%;object-fit:cover">`:'📢'}</div><div class="ch-main"><div class="ch-name">${esc(c.name||'Canal')}</div><div style="font-size:13px;color:#66756e">${esc(c.description||'')}</div><div class="ch-meta">${(c.followers||[]).length} seguidores</div></div>${own?'':`<button id="follow" class="ch-btn ${following?'alt':''}">${following?'Deixar de seguir':'Seguir'}</button>`}</div>${own?`<div class="ch-form"><textarea id="postText" maxlength="1000" rows="3" placeholder="Escreva uma publicação..."></textarea><input id="postImage" placeholder="Link de imagem (opcional)"><button id="publish" class="ch-btn">Publicar</button></div>`:''}<div style="font-weight:800;margin:14px 0 4px">Publicações</div><div id="posts">Carregando...</div>`;
 if(!own){body.querySelector('#follow').onclick=async()=>{const b=body.querySelector('#follow');b.disabled=true;try{await updateDoc(ref,{followers:following?arrayRemove(me.uid):arrayUnion(me.uid),updatedAt:serverTimestamp()});openChannel(id)}catch{alert('Não foi possível alterar agora.');b.disabled=false}}}
 if(own){body.querySelector('#publish').onclick=async()=>{const text=body.querySelector('#postText').value.trim(),image=body.querySelector('#postImage').value.trim();if(!text&&!image)return alert('Escreva algo ou coloque uma imagem.');const b=body.querySelector('#publish');b.disabled=true;b.textContent='Publicando...';try{const p=await addDoc(collection(db,'channels',id,'posts'),{ownerId:me.uid,text,image,createdAt:serverTimestamp()});try{const token=await auth.currentUser.getIdToken();fetch('/api/channel-push',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({channelId:id,postId:p.id}),cache:'no-store'}).catch(()=>{})}catch{}openChannel(id)}catch(e){console.warn(e);alert('Não foi possível publicar.');b.disabled=false;b.textContent='Publicar'}}}
 const ps=await getDocs(query(collection(db,'channels',id,'posts'),orderBy('createdAt','desc'),limit(50)));const box=body.querySelector('#posts');if(ps.empty)box.innerHTML='<div>Ainda não há publicações.</div>';else{box.innerHTML='';ps.forEach(p=>{const d=p.data(),el=document.createElement('div');el.className='ch-post';el.innerHTML=`<div>${esc(d.text||'')}</div>${d.image?`<img src="${esc(d.image)}" alt="Imagem da publicação">`:''}`;box.appendChild(el)})}}
 catch(e){console.warn(e);body.innerHTML='Não foi possível abrir este canal.'}}
 onAuthStateChanged(auth,u=>{me=u||null;if(u){setTimeout(ensureButton,250);if(!openedFromUrl){const id=new URLSearchParams(location.search).get('channel');if(id){openedFromUrl=true;setTimeout(()=>openChannel(id),500)}}}else document.getElementById('channelsBtn')?.remove()});
}
