(()=>{
  const STYLE='chamaUniversalAvatarStyle';
  const photoCache=new Map(), pending=new Map();
  const $=id=>document.getElementById(id);
  function css(){if($(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent='.chama-user-photo,.chama-chat-photo{width:44px;height:44px;border-radius:50%;object-fit:cover;display:block}.chama-photo-wrap{width:44px;height:44px;border-radius:50%;overflow:hidden;display:grid;place-items:center;background:#dff4ea;color:#0b7a53;font-weight:800;flex:0 0 44px}';document.head.appendChild(s)}
  async function fs(){const [a,f]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js')]);const app=a.getApps()[0];if(!app)throw new Error('Firebase ainda não inicializado');return{db:f.getFirestore(app),doc:f.doc,getDoc:f.getDoc,getDocs:f.getDocs,collection:f.collection,query:f.query,limit:f.limit}}
  function safe(url){const v=String(url||'').trim();if(!v)return '';try{const u=new URL(v,location.origin);return u.origin===location.origin&&u.pathname==='/api/media'&&u.searchParams.get('key')?u.href:''}catch{return ''}}
  async function loadProfiles(){try{const x=await fs(),snap=await x.getDocs(x.query(x.collection(x.db,'publicProfiles'),x.limit(100)));snap.forEach(d=>{const p=d.data()||{};const uid=d.id;const email=String(p.email||'').trim().toLowerCase();const url=safe(p.photoUrl);photoCache.set(uid,url);if(email)photoCache.set('email:'+email,{uid,url,nome:p.nome||''})});return true}catch(e){console.warn('avatar profiles',e);return false}}
  async function photo(uid){if(!uid)return '';if(photoCache.has(uid))return typeof photoCache.get(uid)==='string'?photoCache.get(uid):photoCache.get(uid)?.url||'';if(pending.has(uid))return pending.get(uid);const job=(async()=>{try{const x=await fs(),s=await x.getDoc(x.doc(x.db,'publicProfiles',uid));const u=s.exists()?safe(s.data()?.photoUrl):'';photoCache.set(uid,u);return u}catch(e){console.warn('avatar',e);photoCache.set(uid,'');return ''}})();pending.set(uid,job);try{return await job}finally{pending.delete(uid)}}
  function put(el,url,letter){if(!el)return;const safeUrl=safe(url);el.innerHTML='';if(safeUrl){const img=document.createElement('img');img.className=el.id==='chatAvatar'?'chama-chat-photo':'chama-user-photo';img.alt='Foto de perfil';img.src=safeUrl;img.onerror=()=>{el.textContent=letter||'👤'};el.appendChild(img)}else el.textContent=letter||'👤'}
  async function applyRow(row){const avatar=row.querySelector('.avatar');if(!avatar)return;let uid=row.dataset.uid||'';if(!uid){const email=String(row.querySelector('.user-email')?.textContent||'').trim().toLowerCase();const found=photoCache.get('email:'+email);if(found){uid=found.uid;row.dataset.uid=uid;put(avatar,found.url,(row.querySelector('.user-name')?.textContent||found.nome||'U').slice(0,1).toUpperCase());return}if(email){await loadProfiles();const f=photoCache.get('email:'+email);if(f){row.dataset.uid=f.uid;put(avatar,f.url,(row.querySelector('.user-name')?.textContent||f.nome||'U').slice(0,1).toUpperCase());return}}}if(uid){const url=await photo(uid);put(avatar,url,(row.querySelector('.user-name')?.textContent||'U').slice(0,1).toUpperCase())}}
  async function scan(){const list=$('usersList');if(list){const rows=[...list.querySelectorAll('.user')];if(rows.length&&!photoCache.has('__profilesLoaded')){await loadProfiles();photoCache.set('__profilesLoaded','1')}for(const row of rows)await applyRow(row)}const u=window.__chamaActiveUser;const chat=$('chatAvatar');if(u&&chat){const url=await photo(u.id);put(chat,url,String(u.nome||'U').slice(0,1).toUpperCase())}}
  function install(){css();let tries=0;const boot=()=>{scan();if(++tries<20&&!window.__chamaAvatarBoot) setTimeout(boot,500)};window.__chamaAvatarBoot=true;boot();new MutationObserver(()=>scan()).observe(document.body,{childList:true,subtree:true});setInterval(scan,5000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();