import{getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
const cfg={apiKey:"AIzaSyCcAVkmLUKPcEMZ5erDswbOQ8eO493pl2I",authDomain:"chama-cfc28.firebaseapp.com",projectId:"chama-cfc28",storageBucket:"chama-cfc28.firebasestorage.app",messagingSenderId:"680045231088",appId:"1:680045231088:web:8db35684e4b56a320ebb35"};
const app=getApps()[0]||initializeApp(cfg),auth=getAuth(app);let me=null;const PREFIX='__CHAMA_PRODUCT_CONTEXT__';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const safe=v=>{try{const u=new URL(String(v||''));return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
function style(){if(document.getElementById('ctxStyle'))return;const s=document.createElement('style');s.id='ctxStyle';s.textContent=`.ctx-btn{width:100%;border:1px solid #0b7a53;background:#eef9f4;color:#087650;padding:10px;border-radius:10px;font-weight:850;font-size:13px;margin-top:7px}.ctx-msg{display:grid;grid-template-columns:78px minmax(0,1fr);gap:10px;background:#fff;border:1px solid #dce8e2;border-radius:14px;padding:9px;max-width:330px}.ctx-msg-img{width:78px;height:78px;border-radius:10px;background:#eef4f1;overflow:hidden;display:grid;place-items:center;font-size:11px;color:#667}.ctx-msg-img img{width:100%;height:100%;object-fit:cover}.ctx-msg-k{font-size:10px;font-weight:900;color:#087650;text-transform:uppercase}.ctx-msg-title{font-size:14px;font-weight:850;line-height:1.2;margin-top:2px}.ctx-msg-meta{font-size:12px;color:#68766f;margin-top:4px}.ctx-msg-link{display:inline-block;margin-top:6px;color:#087650;font-weight:850;text-decoration:none}.ctx-quick{display:flex;gap:5px;overflow:auto;margin-top:6px;max-width:330px}.ctx-quick button{white-space:nowrap;border:1px solid #cde5da;background:#fff;color:#087650;border-radius:999px;padding:6px 9px;font-size:11px;font-weight:750}`;document.head.appendChild(s)}
function productFromCard(card){return{title:card.querySelector('.product-title')?.textContent?.trim()||'Produto',price:card.querySelector('.product-price')?.textContent?.trim()||'',img:card.querySelector('img')?.src||'',link:card.querySelector('a.buy')?.href||'',platform:card.querySelector('.badge')?.textContent?.trim()||''}}
function submitStructuredProduct(product,intent='ask'){if(!me)return alert('Entre no Chama para conversar.');const input=document.getElementById('messageInput'),form=document.getElementById('composer'),active=document.getElementById('activeChat');if(!input||!form||!active||active.classList.contains('hidden'))return alert('Abra uma conversa antes de enviar o produto.');const payload={type:'product',intent,title:product.title||'Produto',price:product.price||'',image:product.img||product.image||'',link:product.link||'',platform:product.platform||''};input.value=PREFIX+JSON.stringify(payload);input.dispatchEvent(new Event('input',{bubbles:true}));document.getElementById('catalogModal')?.classList.add('hidden');if(form.requestSubmit)form.requestSubmit();else form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))}
function startContext(product){submitStructuredProduct(product,'ask')}
function enhance(){document.querySelectorAll('#catalogGrid .product').forEach(card=>{if(card.querySelector('.ctx-btn'))return;const b=document.createElement('button');b.className='ctx-btn';b.textContent='💬 Chamar sobre este produto';b.onclick=e=>{e.preventDefault();e.stopPropagation();try{startContext(productFromCard(card))}catch(err){console.error(err);alert('Não consegui abrir a conversa sobre este produto.')}};card.querySelector('.product-body')?.appendChild(b)})}
function rawMessageText(b){const clone=b.cloneNode(true);clone.querySelectorAll('.time,.msg-time,[data-time]').forEach(x=>x.remove());return (clone.textContent||'').trim()}
function parsePayload(raw){if(!raw.startsWith(PREFIX))return null;const json=raw.slice(PREFIX.length).trim();try{return JSON.parse(json)}catch{const end=json.lastIndexOf('}');if(end<0)return null;try{return JSON.parse(json.slice(0,end+1))}catch{return null}}}
function renderMessages(){document.querySelectorAll('#messages .bubble').forEach(b=>{if(b.dataset.ctxDone)return;const raw=rawMessageText(b),p=parsePayload(raw);if(!p)return;b.dataset.ctxDone='1';b.dataset.linksReady='1';const img=safe(p.image),link=safe(p.link),time=b.querySelector('.time,.msg-time,[data-time]')?.cloneNode(true);const kicker=p.intent==='ask'?'Conversa sobre este produto':'Produto compartilhado';b.innerHTML=`<div class="ctx-msg"><div class="ctx-msg-img">${img?`<img src="${esc(img)}" loading="lazy" alt="${esc(p.title||'Produto')}">`:'🛍️'}</div><div><div class="ctx-msg-k">${esc(kicker)}</div><div class="ctx-msg-title">${esc(p.title||'Produto')}</div><div class="ctx-msg-meta">${esc(p.platform||'')}${p.platform&&p.price?' • ':''}${esc(p.price||'')}</div>${link?`<a class="ctx-msg-link" href="${esc(link)}" target="_blank" rel="noopener">Ver produto →</a>`:''}</div></div><div class="ctx-quick"></div>`;const q=b.querySelector('.ctx-quick');if(p.intent==='ask')['Ainda está disponível?','Tem meu tamanho?','Quais cores/variações?','Qual o frete?'].forEach(t=>{const x=document.createElement('button');x.type='button';x.textContent=t;x.onclick=()=>{const i=document.getElementById('messageInput');if(i){i.value=t;i.focus()}};q.appendChild(x)});if(time)b.appendChild(time)})}
function scan(){enhance();renderMessages()}
style();new MutationObserver(()=>{clearTimeout(window.__ctxM);window.__ctxM=setTimeout(scan,50)}).observe(document.body,{childList:true,subtree:true});document.addEventListener('click',()=>setTimeout(scan,70),true);onAuthStateChanged(auth,u=>{me=u||null;scan()});scan();