import{getApps,getApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import{getFirestore,collection,query,where,onSnapshot,orderBy,limit,doc,updateDoc,serverTimestamp,FieldPath}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const app=getApps().length?getApp():null;if(!app)throw new Error('Firebase não iniciado');const auth=getAuth(app),db=getFirestore(app);
let stopChats=null,stopUsers=null,chatMap=new Map(),chatById=new Map(),uidEmail=new Map(),messageStops=new Map(),unreadMap=new Map(),currentUid='',activeChatId='';
function addStyle(){if(document.getElementById('conversationListStyle'))return;const s=document.createElement('style');s.id='conversationListStyle';s.textContent=`
#usersList .user{position:relative;min-height:74px;padding-right:76px!important}
#usersList .user-main{flex:1!important;min-width:0!important}
#usersList .user-name{font-size:16px;line-height:1.2;margin-bottom:4px}
#usersList .user-name.chama-unread-name{font-weight:900;color:#0b7a53}
#usersList .conversation-preview{display:block;color:#6a756f;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:100%}
#usersList .conversation-preview.chama-unread-preview{font-weight:750;color:#31443b}
#usersList .conversation-time{position:absolute;right:15px;top:15px;font-size:11px;color:#7a8580;white-space:nowrap}
#usersList .conversation-time.recent{color:#0b7a53;font-weight:800}
#usersList .conversation-unread{position:absolute;right:15px;top:39px;min-width:22px;height:22px;padding:0 6px;border-radius:999px;background:#18a566;color:#fff;display:flex;align-items:center;justify-content:center;font-size:11px;line-height:1;font-weight:900;box-shadow:0 1px 2px #0002}
#usersList .conversation-unread.hidden-unread{display:none!important}
#usersList .user-email{display:none!important}
@media(max-width:700px){#usersList .user{min-height:82px;padding:13px 76px 13px 16px!important}#usersList .avatar{width:50px;height:50px;flex:0 0 50px}#usersList .user-name{font-size:17px}#usersList .conversation-preview{font-size:14px}#usersList .conversation-unread{top:43px}}
`;document.head.appendChild(s)}
function cleanPreview(v=''){let t=String(v||'').trim();if(!t)return 'Toque para iniciar uma conversa';if(t.startsWith('__CHAMA_PRODUCT_CONTEXT__'))return '🛍️ Produto compartilhado';if(t.startsWith('__CHAMA_MEDIA__'))return '📎 Mídia';if(t.length>65)t=t.slice(0,62)+'...';return t.replace(/\s+/g,' ')}
function stampValue(v){const d=v?.toDate?.();return d?d.getTime():0}
function fmt(v){const d=v?.toDate?.();if(!d)return '';const now=new Date(),same=now.toDateString()===d.toDateString();if(same)return d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});const diff=now-d;if(diff<7*86400000)return d.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','');return d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}
function emailOf(row){return (row.querySelector('.user-email')?.textContent||'').trim().toLowerCase()}
function rebuildChatMap(){chatMap.clear();for(const c of chatById.values()){const email=(uidEmail.get(c._otherUid)||'').toLowerCase();if(email)chatMap.set(email,c)}decorate()}
async function markRead(chatId){if(!chatId||!currentUid)return;unreadMap.set(chatId,0);decorate();try{await updateDoc(doc(db,'chats',chatId),new FieldPath('lastReadAt',currentUid),serverTimestamp())}catch(e){console.warn('Não foi possível marcar conversa como lida:',e)}}
function ensureMessageWatch(chatId){if(messageStops.has(chatId)||!currentUid)return;const stop=onSnapshot(query(collection(db,'chats',chatId,'messages'),orderBy('createdAt','desc'),limit(100)),snap=>{const c=chatById.get(chatId)||{},readAt=stampValue(c.lastReadAt?.[currentUid]);let count=0;snap.forEach(d=>{const m=d.data()||{},t=stampValue(m.createdAt);if(m.senderId!==currentUid&&t>readAt)count++});if(activeChatId===chatId&&!document.hidden){if(count>0)markRead(chatId);else{unreadMap.set(chatId,0);decorate()}return}unreadMap.set(chatId,count);decorate()},()=>{});messageStops.set(chatId,stop)}
function decorate(){const list=document.getElementById('usersList');if(!list)return;const rows=[...list.querySelectorAll('.user')];for(const row of rows){const email=emailOf(row),c=chatMap.get(email);if(c)row.dataset.chatId=c._id;let preview=row.querySelector('.conversation-preview');if(!preview){preview=document.createElement('span');preview.className='conversation-preview';const main=row.querySelector('.user-main')||row.querySelector('.user-name')?.parentElement;if(main)main.appendChild(preview)}if(preview)preview.textContent=c?cleanPreview(c.lastMessage):'Toque para iniciar uma conversa';let time=row.querySelector('.conversation-time');if(!time){time=document.createElement('span');time.className='conversation-time';row.appendChild(time)}if(time){time.textContent=c?fmt(c.updatedAt):'';time.classList.toggle('recent',!!c&&stampValue(c.updatedAt)>Date.now()-86400000)}let badge=row.querySelector('.conversation-unread');if(!badge){badge=document.createElement('span');badge.className='conversation-unread hidden-unread';badge.setAttribute('aria-label','Mensagens não lidas');row.appendChild(badge)}const unread=c?(unreadMap.get(c._id)||0):0;if(badge){badge.textContent=unread>99?'99+':String(unread);badge.classList.toggle('hidden-unread',unread<=0)}row.querySelector('.user-name')?.classList.toggle('chama-unread-name',unread>0);preview?.classList.toggle('chama-unread-preview',unread>0);if(!row.dataset.unreadBound){row.dataset.unreadBound='1';row.addEventListener('click',()=>{const id=row.dataset.chatId;if(id){activeChatId=id;markRead(id)}})}}const ordered=rows.sort((a,b)=>{const ca=chatMap.get(emailOf(a)),cb=chatMap.get(emailOf(b)),ta=stampValue(ca?.updatedAt),tb=stampValue(cb?.updatedAt);if(tb!==ta)return tb-ta;return (a.querySelector('.user-name')?.textContent||'').localeCompare(b.querySelector('.user-name')?.textContent||'','pt-BR')});ordered.forEach(r=>list.appendChild(r))}
function watchUsers(u){if(stopUsers){stopUsers();stopUsers=null}uidEmail.clear();if(!u)return;stopUsers=onSnapshot(collection(db,'users'),snap=>{uidEmail.clear();snap.forEach(d=>{const x=d.data()||{},uid=x.uid||d.id,email=(x.email||'').trim().toLowerCase();if(uid&&email)uidEmail.set(uid,email)});rebuildChatMap()},()=>{})}
function watchChats(u){if(stopChats){stopChats();stopChats=null}for(const stop of messageStops.values())stop();messageStops.clear();chatMap.clear();chatById.clear();unreadMap.clear();currentUid=u?.uid||'';activeChatId='';if(!u)return;stopChats=onSnapshot(query(collection(db,'chats'),where('participants','array-contains',u.uid)),snap=>{const live=new Set();chatById.clear();snap.forEach(d=>{const c=d.data()||{},other=(c.participants||[]).find(x=>x!==u.uid);if(!other)return;const enriched={...c,_id:d.id,_otherUid:other};chatById.set(d.id,enriched);live.add(d.id);ensureMessageWatch(d.id)});for(const [id,stop] of messageStops){if(!live.has(id)){stop();messageStops.delete(id);unreadMap.delete(id)}}rebuildChatMap()},()=>{})}
function start(){addStyle();const list=document.getElementById('usersList');if(!list)return setTimeout(start,100);new MutationObserver(()=>setTimeout(decorate,30)).observe(list,{childList:true,subtree:true});document.getElementById('backBtn')?.addEventListener('click',()=>{activeChatId=''});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&activeChatId)markRead(activeChatId)});onAuthStateChanged(auth,u=>{watchUsers(u);watchChats(u);setTimeout(decorate,300)});decorate()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();