(()=>{
  const STYLE_ID='chamaEngagementStyleV3';let me=null,db=null,fs=null,isAdmin=false,observer=null;
  const cleanId=v=>String(v||'').replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,180);
  function style(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`[data-engagement-id]{max-width:100%;box-sizing:border-box;overflow:hidden}.chama-engagement{width:100%;max-width:100%;box-sizing:border-box;display:flex;align-items:center;gap:4px;padding:6px;border-top:1px solid #e8ecea;background:#fff;font-size:12px;color:#52615a;overflow:hidden}.chama-engagement button,.chama-engagement [data-k=views]{min-width:0;min-height:32px;box-sizing:border-box;border:0;background:#eef7f2;color:#0b7a53;border-radius:999px;padding:6px 8px;font-size:12px;font-weight:850;line-height:1;display:inline-flex;align-items:center;justify-content:center;gap:3px;white-space:nowrap}.chama-engagement button{cursor:pointer}.chama-engagement [data-k=shares]{flex:1 1 auto;padding-left:8px;padding-right:8px}.chama-engagement [data-k=likes],.chama-engagement [data-k=views]{flex:0 0 auto}.chama-engagement [data-k=views]{background:#f4f6f5;color:#52615a}.chama-engagement .liked{background:#ffe9ec;color:#b4233c}.chama-engagement-admin{margin-left:0!important;background:#fff5dc!important;color:#895800!important;min-width:32px!important;width:32px!important;padding:6px!important;flex:0 0 32px!important}.chama-affiliate-day-top .chama-engagement{margin:6px 0 0;border-radius:10px}.chama-targeted-banner .chama-engagement{grid-column:1/-1;padding:5px}@media(max-width:340px){.chama-engagement{gap:3px;padding:5px 3px}.chama-engagement button,.chama-engagement [data-k=views]{font-size:11px;padding:5px 6px}.chama-engagement-admin{min-width:29px!important;width:29px!important;flex-basis:29px!important}}`;document.head.appendChild(s)}
  function total(d,k){return Math.max(0,Number(d?.[k]||0)+Number(d?.admin?.[k]||0))}
  async function view(id){const day=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}),key=`chama_view_${id}_${me.uid}_${day}`;if(localStorage.getItem(key))return;localStorage.setItem(key,'1');try{await fs.setDoc(fs.doc(db,'engagement',id),{views:fs.increment(1),updatedAt:fs.serverTimestamp()},{merge:true})}catch{localStorage.removeItem(key)}}
  async function load(bar,id){try{const [s,l]=await Promise.all([fs.getDoc(fs.doc(db,'engagement',id)),fs.getDoc(fs.doc(db,'engagement',id,'likes',me.uid))]),d=s.data()||{};bar.querySelector('[data-k=likes]').textContent=`❤️ ${total(d,'likes')}`;bar.querySelector('[data-k=shares]').textContent=`📤 Compartilhar ${total(d,'shares')}`;bar.querySelector('[data-k=views]').textContent=`👁️ ${total(d,'views')}`;bar.querySelector('[data-k=likes]').classList.toggle('liked',l.exists());bar.dataset.liked=l.exists()?'1':'0'}catch(e){console.warn('Chama: contadores não carregaram',e)}}
  async function like(bar,id){const liked=bar.dataset.liked==='1',ref=fs.doc(db,'engagement',id,'likes',me.uid);try{if(liked)await fs.deleteDoc(ref);else await fs.setDoc(ref,{uid:me.uid,createdAt:fs.serverTimestamp()});await fs.setDoc(fs.doc(db,'engagement',id),{likes:fs.increment(liked?-1:1),updatedAt:fs.serverTimestamp()},{merge:true});load(bar,id)}catch(e){alert('Não foi possível registrar a curtida agora.')}}
  async function share(bar,id,host){const url=host.querySelector('a[href^="http"]')?.href||location.href,title=host.querySelector('strong,.chama-community-title,.chama-affiliate-day-title')?.textContent||'Chama';try{if(navigator.share)await navigator.share({title,url});else await navigator.clipboard.writeText(url);await fs.setDoc(fs.doc(db,'engagement',id),{shares:fs.increment(1),updatedAt:fs.serverTimestamp()},{merge:true});load(bar,id)}catch(e){if(e?.name!=='AbortError')alert('Não foi possível compartilhar agora.')}}
  async function edit(bar,id){if(!isAdmin)return;const s=await fs.getDoc(fs.doc(db,'engagement',id)),d=s.data()?.admin||{},likes=prompt('Curtidas acrescentadas pelo admin:',String(d.likes||0));if(likes===null)return;const shares=prompt('Compartilhamentos acrescentados pelo admin:',String(d.shares||0));if(shares===null)return;const views=prompt('Visualizações acrescentadas pelo admin:',String(d.views||0));if(views===null)return;const num=v=>Math.max(0,Math.floor(Number(v)||0));try{await fs.setDoc(fs.doc(db,'engagement',id),{admin:{likes:num(likes),shares:num(shares),views:num(views)},updatedAt:fs.serverTimestamp(),adminUpdatedBy:me.uid},{merge:true});load(bar,id)}catch{alert('Não foi possível editar os números.')}}
  function install(host){if(!me||host.querySelector(':scope > .chama-engagement'))return;const id=cleanId(host.dataset.engagementId);if(!id)return;const bar=document.createElement('div');bar.className='chama-engagement';bar.innerHTML='<button data-k="likes" type="button" aria-label="Curtir" title="Curtir">❤️ 0</button><button data-k="shares" type="button" aria-label="Compartilhar" title="Compartilhar">📤 Compartilhar 0</button><span data-k="views" aria-label="Visualizações" title="Visualizações">👁️ 0</span>'+(isAdmin?'<button class="chama-engagement-admin" type="button" aria-label="Editar números" title="Editar números">✏️</button>':'');host.appendChild(bar);bar.querySelector('[data-k=likes]').onclick=()=>like(bar,id);bar.querySelector('[data-k=shares]').onclick=()=>share(bar,id,host);bar.querySelector('.chama-engagement-admin')?.addEventListener('click',()=>edit(bar,id));load(bar,id);view(id).then(()=>load(bar,id))}
  function scan(){document.querySelectorAll('[data-engagement-id]').forEach(install)}
  async function start(attempt=0){style();try{const appMod=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js'),app=appMod.getApps()[0];if(!app){if(attempt<30)setTimeout(()=>start(attempt+1),150);return}const authMod=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js');fs=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js');db=fs.getFirestore(app);authMod.onAuthStateChanged(authMod.getAuth(app),async u=>{me=u||null;isAdmin=false;if(me){try{const s=await fs.getDoc(fs.doc(db,'users',me.uid));isAdmin=s.data()?.admin===true}catch{}scan()}});observer=new MutationObserver(()=>scan());observer.observe(document.body,{childList:true,subtree:true})}catch(e){console.warn(e)}}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>start(),{once:true}):start();
})();
