import{getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getAuth}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import{getFirestore,collection,query,where,getDocs,limit,addDoc,doc,setDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyCcAVkmLUKPcEMZ5erDswbOQ8eO493pl2I",authDomain:"chama-cfc28.firebaseapp.com",projectId:"chama-cfc28",storageBucket:"chama-cfc28.firebasestorage.app",messagingSenderId:"680045231088",appId:"1:680045231088:web:8db35684e4b56a320ebb35"};
const app=getApps()[0]||initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const PREFIX="__CHAMA_MEDIA__";
let recorder=null,chunks=[];

function addStyles(){if(document.getElementById("mediaChatStyle"))return;const s=document.createElement("style");s.id="mediaChatStyle";s.textContent=`
.media-tools{display:flex;gap:5px;align-items:center}.media-btn{border:0;background:#eef4f1;color:#0b7a53;width:38px;height:38px;border-radius:50%;font-size:18px;display:grid;place-items:center;cursor:pointer}.media-btn.recording{background:#ffe7e7;color:#b42318;animation:pulse 1s infinite}.media-progress{position:fixed;left:50%;bottom:85px;transform:translateX(-50%);z-index:99;background:#14221c;color:#fff;padding:10px 14px;border-radius:999px;font-size:13px;box-shadow:0 8px 30px #0003}.chat-media{display:block;max-width:100%;border-radius:12px;margin-bottom:4px}.chat-media.image{max-height:340px;object-fit:cover}.chat-media.video{width:min(320px,70vw);background:#000}.chat-media.audio{width:min(300px,70vw)}.media-name{font-size:12px;color:#55615b;margin:4px 0}.media-error{font-size:13px;color:#b42318}@keyframes pulse{50%{opacity:.55}}
@media(max-width:700px){.composer{gap:5px}.media-btn{width:36px;height:36px}.composer input{min-width:0;padding-left:12px;padding-right:12px}}
`;document.head.appendChild(s)}
function toast(text){let n=document.getElementById("mediaProgress");if(!n){n=document.createElement("div");n.id="mediaProgress";n.className="media-progress";document.body.appendChild(n)}n.textContent=text;n.classList.remove("hidden");return()=>n.classList.add("hidden")}
function currentChatOpen(){return document.getElementById("activeChat")&&!document.getElementById("activeChat").classList.contains("hidden")}
async function resolveReceiver(){const email=(document.getElementById("chatEmail")?.textContent||"").trim();if(!email)return null;const s=await getDocs(query(collection(db,"users"),where("email","==",email),limit(1)));let u=null;s.forEach(d=>u={uid:d.id,...d.data()});return u}
async function sendMediaMessage(meta){const me=auth.currentUser;if(!me)throw new Error("Faça login novamente.");const other=await resolveReceiver();if(!other?.uid)throw new Error("Não consegui identificar o contato desta conversa.");const ids=[me.uid,other.uid].sort(),chatId=ids.join("_");const text=PREFIX+JSON.stringify(meta);const label=meta.kind==="image"?"📷 Imagem":meta.kind==="audio"?"🎤 Áudio":"🎥 Vídeo";await addDoc(collection(db,"chats",chatId,"messages"),{text,senderId:me.uid,receiverId:other.uid,createdAt:serverTimestamp()});await setDoc(doc(db,"chats",chatId),{participants:ids,lastMessage:label,updatedAt:serverTimestamp()},{merge:true})}
async function upload(file){if(!currentChatOpen())return alert("Abra uma conversa antes de enviar mídia.");const me=auth.currentUser;if(!me)return alert("Faça login novamente.");const kind=file.type.startsWith("image/")?"image":file.type.startsWith("audio/")?"audio":file.type.startsWith("video/")?"video":"";if(!kind)return alert("Formato não permitido.");const max={image:5,audio:10,video:25}[kind];if(file.size>max*1024*1024)return alert(`Arquivo muito grande. Limite: ${max} MB.`);const hide=toast("Enviando mídia...");try{const token=await me.getIdToken();const r=await fetch("/api/media",{method:"POST",headers:{"Authorization":"Bearer "+token,"Content-Type":file.type||"application/octet-stream","X-File-Name":encodeURIComponent(file.name||kind)},body:file});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Falha no upload.");await sendMediaMessage({kind:d.kind,url:d.url,name:(file.name||kind).slice(0,120)});hide()}catch(e){hide();alert(e.message||"Não foi possível enviar a mídia.")}}
function pick(accept){const i=document.createElement("input");i.type="file";i.accept=accept;i.style.display="none";document.body.appendChild(i);i.onchange=async()=>{const f=i.files?.[0];i.remove();if(f)await upload(f)};i.click()}
async function toggleRecord(btn){if(recorder&&recorder.state==="recording"){recorder.stop();btn.classList.remove("recording");btn.textContent="🎤";return}if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined")return alert("Seu navegador não permite gravação de áudio aqui.");if(!currentChatOpen())return alert("Abra uma conversa antes de gravar áudio.");try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];let mime="";for(const t of["audio/webm;codecs=opus","audio/webm","audio/mp4"]){if(MediaRecorder.isTypeSupported?.(t)){mime=t;break}}recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const type=recorder.mimeType||"audio/webm";const blob=new Blob(chunks,{type});const ext=type.includes("mp4")?"m4a":"webm";recorder=null;chunks=[];if(blob.size)await upload(new File([blob],`audio-${Date.now()}.${ext}`,{type}))};recorder.start();btn.classList.add("recording");btn.textContent="■";toast("Gravando áudio... toque ■ para enviar")()}catch{alert("Não foi possível acessar o microfone.")}}
function installTools(){const form=document.getElementById("composer"),input=document.getElementById("messageInput");if(!form||!input||document.getElementById("mediaTools"))return;addStyles();const w=document.createElement("div");w.id="mediaTools";w.className="media-tools";const img=document.createElement("button"),mic=document.createElement("button"),vid=document.createElement("button");for(const b of[img,mic,vid]){b.type="button";b.className="media-btn"}img.textContent="📷";img.title="Enviar imagem";mic.textContent="🎤";mic.title="Gravar áudio";vid.textContent="🎥";vid.title="Enviar vídeo";img.onclick=()=>pick("image/*");mic.onclick=()=>toggleRecord(mic);vid.onclick=()=>pick("video/*");w.append(img,mic,vid);form.insertBefore(w,input)}
function renderBubble(b){if(!b||b.dataset.mediaReady==="1")return;const first=[...b.childNodes].find(n=>n.nodeType===Node.TEXT_NODE&&n.nodeValue?.startsWith(PREFIX));if(!first)return;let m;try{m=JSON.parse(first.nodeValue.slice(PREFIX.length))}catch{return}const time=b.querySelector(".time");b.innerHTML="";let el;if(m.kind==="image"){el=document.createElement("img");el.className="chat-media image";el.loading="lazy";el.alt=m.name||"Imagem";el.src=m.url}else if(m.kind==="audio"){el=document.createElement("audio");el.className="chat-media audio";el.controls=true;el.preload="metadata";el.src=m.url}else if(m.kind==="video"){el=document.createElement("video");el.className="chat-media video";el.controls=true;el.preload="metadata";el.playsInline=true;el.src=m.url}else{const e=document.createElement("div");e.className="media-error";e.textContent="Mídia não suportada";b.appendChild(e)}if(el){el.onerror=()=>{const e=document.createElement("div");e.className="media-error";e.textContent="Não foi possível carregar esta mídia.";el.replaceWith(e)};b.appendChild(el)}if(m.name){const n=document.createElement("div");n.className="media-name";n.textContent=m.name;b.appendChild(n)}if(time)b.appendChild(time);b.dataset.mediaReady="1"}
function scan(){document.querySelectorAll("#messages .bubble").forEach(renderBubble)}
function start(){installTools();scan();const messages=document.getElementById("messages");if(messages)new MutationObserver(scan).observe(messages,{childList:true,subtree:true});new MutationObserver(installTools).observe(document.body,{childList:true,subtree:true})}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",start):start();
