import{getApps,getApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import{getFirestore,doc,getDoc,setDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const app=getApps().length?getApp():null;
if(app){const auth=getAuth(app),db=getFirestore(app);let me=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
async function user(){if(!me)return null;const s=await getDoc(doc(db,'users',me.uid));return s.exists()?{uid:s.id,...s.data()}:null}
function list(u){if(Array.isArray(u.ofertasFeed))return u.ofertasFeed.slice(0,2);const old=u.ofertaDia;if(old?.title)return[old];return[]}
function css(){if(document.getElementById('offersTwoStyle'))return;const s=document.createElement('style');s.id='offersTwoStyle';s.textContent='.ot-modal{position:fixed;inset:0;background:#0009;z-index:1400;display:grid;place-items:center;padding:12px}.ot-card{width:min(480px,100%);max-height:92dvh;overflow:auto;background:#fff;border-radius:20px;padding:18px}.ot-card h3{margin:0 0 8px;color:#0b7a53}.ot-note{font-size:12px;color:#66756e;margin-bottom:12px}.ot-slot{border:1px solid #dce5e0;border-radius:14px;padding:11px;margin:9px 0}.ot-slot b{display:block;margin-bottom:5px}.ot-actions{display:flex;gap:7px}.ot-actions button,.ot-new,.ot-close,.ot-save{border:0;border-radius:10px;padding:10px 12px;font-weight:850}.ot-edit{background:#e8f4ee;color:#0b7a53}.ot-remove{background:#fff0f0;color:#a51d1d}.ot-new,.ot-save{background:#0b7a53;color:#fff}.ot-close{background:#edf2ef;color:#42554c}.ot-field{display:grid;gap:4px;margin:9px 0}.ot-field input,.ot-field textarea{border:1px solid #ccd6d1;border-radius:10px;padding:10px;font:inherit}.ot-field textarea{min-height:80px}';document.head.appendChild(s)}
function manage(u){document.querySelector('.ot-modal')?.remove();const arr=list(u),m=document.createElement('div');m.className='ot-modal';m.innerHTML=`<div class="ot-card"><h3>🔥 Minhas ofertas</h3><div class="ot-note">Até 2 ofertas ativas. Você pode editar cada uma quantas vezes quiser.</div><div>${arr.map((o,i)=>`<div class="ot-slot"><b>${esc(o.title||'Oferta '+(i+1))}</b><div class="ot-actions"><button class="ot-edit" data-e="${i}">Editar</button><button class="ot-remove" data-r="${i}">Remover</button></div></div>`).join('')||'<div class="ot-note">Você ainda não publicou ofertas.</div>'}</div>${arr.length<2?'<button class="ot-new">+ Nova oferta</button>':''} <button class="ot-close">Fechar</button></div>`;document.body.appendChild(m);m.querySelector('.ot-close').onclick=()=>m.remove();m.querySelector('.ot-new')?.addEventListener('click',()=>edit(u,arr,-1));m.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>edit(u,arr,+b.dataset.e));m.querySelectorAll('[data-r]').forEach(b=>b.onclick=async()=>{if(!confirm('Remover esta oferta?'))return;arr.splice(+b.dataset.r,1);await save(arr);m.remove();location.reload()});}
function edit(u,arr,idx){document.querySelector('.ot-modal')?.remove();const o=idx>=0?arr[idx]:{},m=document.createElement('div');m.className='ot-modal';m.innerHTML=`<div class="ot-card"><h3>${idx>=0?'Editar oferta':'Nova oferta'}</h3><div class="ot-field"><label>Título</label><input id="ott" maxlength="120" value="${esc(o.title||'')}"></div><div class="ot-field"><label>Preço</label><input id="otp" value="${esc(o.price||'')}"></div><div class="ot-field"><label>Preço anterior</label><input id="oto" value="${esc(o.oldPrice||'')}"></div><div class="ot-field"><label>Descrição</label><textarea id="otd" maxlength="500">${esc(o.description||'')}</textarea></div><div class="ot-field"><label>Link da imagem</label><input id="oti" value="${esc(o.image||'')}"></div><div class="ot-field"><label>Link de afiliado / compra</label><input id="otl" value="${esc(o.link||'')}"></div><div class="ot-field"><label>Válida até</label><input id="otv" type="date" value="${esc(o.validUntil||today())}"></div><button class="ot-save">Salvar oferta</button> <button class="ot-close">Cancelar</button></div>`;document.body.appendChild(m);m.querySelector('.ot-close').onclick=()=>m.remove();m.querySelector('.ot-save').onclick=async()=>{const title=m.querySelector('#ott').value.trim();if(!title)return alert('Digite o título.');const data={active:true,title,price:m.querySelector('#otp').value.trim(),oldPrice:m.querySelector('#oto').value.trim(),description:m.querySelector('#otd').value.trim(),image:m.querySelector('#oti').value.trim(),link:m.querySelector('#otl').value.trim(),validUntil:m.querySelector('#otv').value||today(),createdAt:o.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(idx>=0)arr[idx]=data;else{if(arr.length>=2)return alert('Limite de 2 ofertas atingido.');arr.push(data)}await save(arr);m.remove();alert('Oferta salva. Você pode editá-la quando quiser.');location.reload()}}
async function save(arr){await setDoc(doc(db,'users',me.uid),{ofertasFeed:arr.slice(0,2),ofertaDia:arr[0]?{...arr[0],updatedAt:serverTimestamp()}:{active:false,updatedAt:serverTimestamp()}},{merge:true})}
function hook(){document.addEventListener('click',async e=>{const b=e.target.closest('#offersNew,#offerOwnBtn');if(!b||!me)return;e.preventDefault();e.stopImmediatePropagation();const u=await user();if(!u||u.tipoPerfil!=='profissional')return alert('O Feed de Ofertas é para Perfil Profissional.');manage(u)},true)}
css();hook();onAuthStateChanged(auth,u=>me=u||null)}