import{getApps,getApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import{getFirestore,doc,getDoc,setDoc,collection,getDocs,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const app=getApps().length?getApp():null;
if(app){
const auth=getAuth(app),db=getFirestore(app);let me=null,myData=null,offers=[];
const norm=v=>String(v||'').trim().toLowerCase();
const esc=(v='')=>String(v).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
const safeUrl=v=>{try{const u=new URL(String(v||''));return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
function css(){if(document.getElementById('offersStyle'))return;const s=document.createElement('style');s.id='offersStyle';s.textContent=`
.offers-top-btn{border:1px solid #ffffff80;background:#fff;color:#a54800;border-radius:12px;padding:9px 11px;font-weight:850;white-space:nowrap}
.offers-modal{position:fixed;inset:0;background:#edf2ef;z-index:950;display:flex;justify-content:center}.offers-modal.hidden{display:none}
.offers-feed{width:min(680px,100%);height:100dvh;background:#f2f5f3;display:flex;flex-direction:column;overflow:hidden}
.offers-head{background:#0b7a53;color:#fff;padding:12px 14px;display:flex;align-items:center;gap:9px;position:sticky;top:0;z-index:4}.offers-head h3{margin:0;flex:1;font-size:20px}.offers-close{border:1px solid #ffffff55;background:#ffffff18;color:#fff;width:42px;height:42px;border-radius:13px;font-size:24px}.offers-new{border:0;background:#fff;color:#0b7a53;padding:10px 12px;border-radius:11px;font-weight:900}
.offers-tools{background:#fff;padding:10px;border-bottom:1px solid #e0e7e3;display:grid;grid-template-columns:1fr 1fr;gap:8px}.offers-tools input{width:100%;border:1px solid #d6dfda;border-radius:999px;padding:10px 13px;background:#f4f7f5;outline:none}
.offers-scroll{flex:1;overflow:auto;padding:10px 9px 24px}.offers-intro{background:linear-gradient(135deg,#e4f7ed,#fff6df);border:1px solid #dce9e2;border-radius:17px;padding:13px;margin-bottom:10px}.offers-intro b{color:#0b7a53}.offers-intro small{display:block;color:#62716a;margin-top:3px}
.offer-item{background:#fff;border:1px solid #dfe7e3;border-radius:18px;overflow:hidden;margin:0 0 12px;box-shadow:0 2px 8px #0000000a}.offer-user{display:flex;align-items:center;gap:9px;padding:11px 12px}.offer-avatar{width:42px;height:42px;border-radius:50%;background:#dff4ea;color:#0b7a53;display:grid;place-items:center;font-weight:900;overflow:hidden;flex:0 0 42px}.offer-avatar img{width:100%;height:100%;object-fit:cover}.offer-user-main{min-width:0;flex:1}.offer-business{font-weight:900;color:#173f33;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.offer-location{font-size:12px;color:#75817b;margin-top:1px}.offer-badge{font-size:10px;background:#fff1df;color:#a54800;border-radius:999px;padding:5px 7px;font-weight:900}
.offer-img{display:block;width:100%;max-height:520px;aspect-ratio:1/1;object-fit:cover;background:#eef3f0}.offer-body{padding:12px}.offer-title{font-size:18px;font-weight:900;color:#173f33;margin:0 0 5px}.offer-desc{font-size:14px;color:#53615a;white-space:pre-wrap;line-height:1.35}.offer-price{display:flex;align-items:baseline;gap:8px;margin:9px 0}.offer-price strong{font-size:23px;color:#0b7a53}.offer-price del{font-size:13px;color:#89918d}.offer-meta{font-size:11px;color:#718078;margin-top:7px}.offer-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:11px}.offer-actions button,.offer-actions a{border:0;border-radius:11px;padding:11px 9px;font-weight:850;text-decoration:none;text-align:center;font-size:13px}.offer-talk{background:#0b7a53;color:#fff}.offer-link{background:#e8f4ee;color:#0b7a53}.offer-catalog{grid-column:1/-1;background:#fff;border:1px solid #cbd9d2!important;color:#0b7a53!important}.offers-empty{background:#fff;border-radius:16px;padding:26px 18px;text-align:center;color:#69756f}
.offer-edit{position:fixed;inset:0;background:#0009;z-index:1100;display:grid;place-items:center;padding:12px}.offer-edit-card{width:min(480px,100%);max-height:92dvh;overflow:auto;background:#fff;border-radius:20px;padding:18px}.offer-edit-card h3{margin:0 0 12px;color:#a54800}.offer-field{display:grid;gap:5px;margin:9px 0}.offer-field label{font-size:12px;font-weight:800}.offer-field input,.offer-field textarea{width:100%;border:1px solid #ccd6d1;border-radius:11px;padding:10px 11px;font:inherit}.offer-field textarea{min-height:85px;resize:vertical}.offer-edit-actions{display:flex;gap:8px;margin-top:12px}.offer-edit-actions button{flex:1;border:0;border-radius:12px;padding:12px;font-weight:850}.offer-save{background:#0b7a53;color:#fff}.offer-remove{background:#fff0f0;color:#a51d1d}.offer-cancel{background:#edf3f0;color:#496159}.offer-own-btn{width:100%;border:1px solid #ffcfaa;background:#fff7ef;color:#a54800;border-radius:13px;padding:12px 14px;font-weight:850}
@media(max-width:520px){.offers-tools{grid-template-columns:1fr}.offers-scroll{padding:8px}.offer-actions{grid-template-columns:1fr 1fr}.offers-head h3{font-size:18px}.offers-new{font-size:12px;padding:9px}}
`;document.head.appendChild(s)}
function money(v){const n=Number(String(v||'').replace(',','.'));return Number.isFinite(n)&&n>0?n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):''}
function today(){return new Date().toISOString().slice(0,10)}
function isActive(u){const o=u.ofertaDia;return u.tipoPerfil==='profissional'&&o?.active&&o?.title&&(!o.validUntil||o.validUntil>=today())}
function avatar(u){const src=safeUrl(u.foto||u.photoURL||u.photo||u.avatar||'');if(src)return `<img src="${esc(src)}" alt="" loading="lazy">`;return esc((u.nomeNegocio||u.nome||u.name||'U').trim().charAt(0).toUpperCase())}
function modal(){let m=document.getElementById('offersModal');if(m)return m;m=document.createElement('div');m.id='offersModal';m.className='offers-modal hidden';m.innerHTML=`<section class="offers-feed"><div class="offers-head"><h3>🔥 Feed de Ofertas</h3><button id="offersNew" class="offers-new hidden" type="button">+ Publicar</button><button class="offers-close" type="button">×</button></div><div class="offers-tools"><input id="offersSearch" placeholder="Buscar produto, loja ou categoria"><input id="offersCity" placeholder="Cidade / região"></div><div class="offers-scroll"><div class="offers-intro"><b>Descubra ofertas e fale direto com quem vende.</b><small>Produtos de afiliados e profissionais do Chama em um só lugar.</small></div><div id="offersList"></div></div></section>`;document.body.appendChild(m);m.querySelector('.offers-close').onclick=()=>m.classList.add('hidden');m.querySelectorAll('.offers-tools input').forEach(i=>i.oninput=render);m.querySelector('#offersNew').onclick=()=>editor(myData||{});return m}
async function loadOffers(){const s=await getDocs(collection(db,'users'));offers=[];s.forEach(d=>{const u={uid:d.id,...d.data()};if(isActive(u))offers.push(u)});offers.sort((a,b)=>(b.ofertaDia?.updatedAt?.seconds||b.ofertaDia?.createdAt?.seconds||0)-(a.ofertaDia?.updatedAt?.seconds||a.ofertaDia?.createdAt?.seconds||0));render()}
function findRow(uid){return [...document.querySelectorAll('#usersList .user')].find(r=>r.dataset.uid===uid)}
function talk(uid){modal().classList.add('hidden');const row=findRow(uid);if(row){row.click();return}alert('Não consegui abrir essa conversa agora. Procure a pessoa na lista do Chama.')}
function catalog(uid){modal().classList.add('hidden');const row=findRow(uid);if(row){row.click();setTimeout(()=>document.getElementById('chatCatalogBtn')?.click(),250);return}location.href=`https://chama.alibr.com.br/?catalogo=${encodeURIComponent(uid)}`}
function render(){const m=modal(),q=norm(m.querySelector('#offersSearch')?.value),city=norm(m.querySelector('#offersCity')?.value),list=offers.filter(u=>{const o=u.ofertaDia||{},hay=norm(`${o.title} ${o.description} ${u.nomeNegocio} ${u.categoriaProfissional} ${u.nome}`),loc=norm(`${u.cidadeProfissional||u.cidade||''} ${u.estado||''}`);return(!q||hay.includes(q))&&(!city||loc.includes(city))});m.querySelector('#offersList').innerHTML=list.length?list.map(u=>{const o=u.ofertaDia||{},p=money(o.price),old=money(o.oldPrice),img=safeUrl(o.image),link=safeUrl(o.link),place=[u.cidadeProfissional||u.cidade,u.estado].filter(Boolean).join(' - ');return `<article class="offer-item" data-offer-uid="${esc(u.uid)}"><div class="offer-user"><div class="offer-avatar">${avatar(u)}</div><div class="offer-user-main"><div class="offer-business">${esc(u.nomeNegocio||u.nome||u.name||'Profissional')}</div><div class="offer-location">${esc(place||u.categoriaProfissional||'Perfil profissional')}</div></div><span class="offer-badge">OFERTA</span></div>${img?`<img class="offer-img" src="${esc(img)}" alt="${esc(o.title)}" loading="lazy">`:''}<div class="offer-body"><div class="offer-title">${esc(o.title)}</div>${o.description?`<div class="offer-desc">${esc(o.description)}</div>`:''}${p?`<div class="offer-price"><strong>${p}</strong>${old?`<del>${old}</del>`:''}</div>`:''}<div class="offer-meta">${u.categoriaProfissional?esc(u.categoriaProfissional)+' • ':''}${o.validUntil?'válida até '+esc(o.validUntil.split('-').reverse().join('/')):'oferta ativa'}</div><div class="offer-actions"><button class="offer-talk" data-talk="${esc(u.uid)}">💬 Conversar</button>${link?`<a class="offer-link" href="${esc(link)}" target="_blank" rel="noopener sponsored">🛒 Ver oferta</a>`:'<button class="offer-link" data-catalog="'+esc(u.uid)+'">🛒 Ver produtos</button>'}<button class="offer-catalog" data-catalog="${esc(u.uid)}">🛍️ Ver catálogo</button></div></div></article>`}).join(''):`<div class="offers-empty">Nenhuma oferta ativa encontrada.<br><small>Os profissionais podem publicar uma oferta pelo botão + Publicar.</small></div>`;m.querySelectorAll('[data-talk]').forEach(b=>b.onclick=()=>talk(b.dataset.talk));m.querySelectorAll('[data-catalog]').forEach(b=>b.onclick=()=>catalog(b.dataset.catalog))}
async function openOffers(){const m=modal();m.classList.remove('hidden');const nb=m.querySelector('#offersNew');nb.classList.toggle('hidden',myData?.tipoPerfil!=='profissional');m.querySelector('#offersList').innerHTML='<div class="offers-empty">Carregando ofertas...</div>';try{await loadOffers()}catch(e){console.warn(e);m.querySelector('#offersList').innerHTML='<div class="offers-empty">Não consegui carregar as ofertas.</div>'}}
function installTopButton(){const top=document.querySelector('.topbar');if(!top||document.getElementById('offersTopBtn')||!me)return;const b=document.createElement('button');b.id='offersTopBtn';b.className='offers-top-btn';b.textContent='🔥 Ofertas';b.onclick=openOffers;top.insertBefore(b,document.getElementById('logoutBtn'))}
function editor(u){document.getElementById('offerEditor')?.remove();const o=u.ofertaDia||{},d=document.createElement('div');d.id='offerEditor';d.className='offer-edit';d.innerHTML=`<div class="offer-edit-card"><h3>🔥 Publicar no Feed de Ofertas</h3><div class="offer-field"><label>Título da oferta</label><input id="ofTitle" maxlength="120" value="${esc(o.title||'')}" placeholder="Ex.: Vestido em promoção"></div><div class="offer-field"><label>Preço promocional</label><input id="ofPrice" inputmode="decimal" value="${esc(o.price||'')}" placeholder="Ex.: 79,90"></div><div class="offer-field"><label>Preço anterior (opcional)</label><input id="ofOldPrice" inputmode="decimal" value="${esc(o.oldPrice||'')}" placeholder="Ex.: 119,90"></div><div class="offer-field"><label>Descrição</label><textarea id="ofDesc" maxlength="500" placeholder="Explique a oferta.">${esc(o.description||'')}</textarea></div><div class="offer-field"><label>Link da imagem</label><input id="ofImage" value="${esc(o.image||'')}" placeholder="https://..."></div><div class="offer-field"><label>Link de afiliado / compra</label><input id="ofLink" value="${esc(o.link||'')}" placeholder="https://..."></div><div class="offer-field"><label>Oferta válida até</label><input id="ofUntil" type="date" value="${esc(o.validUntil||today())}"></div><div class="offer-edit-actions"><button class="offer-cancel">Cancelar</button>${o.active?'<button class="offer-remove">Remover</button>':''}<button class="offer-save">Publicar</button></div></div>`;document.body.appendChild(d);d.querySelector('.offer-cancel').onclick=()=>d.remove();d.onclick=e=>{if(e.target===d)d.remove()};const rm=d.querySelector('.offer-remove');if(rm)rm.onclick=async()=>{if(!confirm('Remover sua oferta atual do feed?'))return;await setDoc(doc(db,'users',me.uid),{ofertaDia:{...o,active:false,updatedAt:serverTimestamp()}},{merge:true});myData={...u,ofertaDia:{...o,active:false}};d.remove();await loadOffers()};d.querySelector('.offer-save').onclick=async()=>{const title=d.querySelector('#ofTitle').value.trim();if(!title)return alert('Digite o título da oferta.');const btn=d.querySelector('.offer-save');btn.disabled=true;btn.textContent='Publicando...';const data={active:true,title,price:d.querySelector('#ofPrice').value.trim(),oldPrice:d.querySelector('#ofOldPrice').value.trim(),description:d.querySelector('#ofDesc').value.trim(),image:d.querySelector('#ofImage').value.trim(),link:d.querySelector('#ofLink').value.trim(),validUntil:d.querySelector('#ofUntil').value||today(),createdAt:o.createdAt||serverTimestamp(),updatedAt:serverTimestamp()};try{await setDoc(doc(db,'users',me.uid),{ofertaDia:data},{merge:true});myData={...u,ofertaDia:data};d.remove();alert('Oferta publicada no Feed do Chama! 🔥');if(!modal().classList.contains('hidden'))await loadOffers()}catch{btn.disabled=false;btn.textContent='Publicar';alert('Não consegui publicar a oferta.')}}}
async function syncOwnProfileOffer(){const pm=document.getElementById('profileModal'),actions=document.getElementById('profileActions');if(!me||!pm||pm.classList.contains('hidden')||!actions)return;document.getElementById('offerOwnBtn')?.remove();const own=document.getElementById('profileEmail')?.textContent===me.email;if(!own)return;try{const s=await getDoc(doc(db,'users',me.uid));if(!s.exists())return;const u={uid:s.id,...s.data()};myData=u;if(u.tipoPerfil!=='profissional')return;const b=document.createElement('button');b.id='offerOwnBtn';b.className='offer-own-btn';b.textContent=u.ofertaDia?.active?'🔥 Editar oferta do feed':'🔥 Publicar no Feed de Ofertas';b.onclick=()=>editor(u);actions.appendChild(b)}catch{}}
function start(){css();document.addEventListener('click',()=>setTimeout(syncOwnProfileOffer,160),true);onAuthStateChanged(auth,async u=>{me=u||null;document.getElementById('offersTopBtn')?.remove();if(!u)return;try{const s=await getDoc(doc(db,'users',u.uid));myData=s.exists()?{uid:s.id,...s.data()}:null}catch{}installTopButton()})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
}
