import{getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import{getFirestore,doc,setDoc,onSnapshot,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyCcAVkmLUKPcEMZ5erDswbOQ8eO493pl2I",authDomain:"chama-cfc28.firebaseapp.com",projectId:"chama-cfc28",storageBucket:"chama-cfc28.firebasestorage.app",messagingSenderId:"680045231088",appId:"1:680045231088:web:8db35684e4b56a320ebb35"};
const app=getApps()[0]||initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
let uid='',timer=null,stopWatch=null,lastWrite=0;
function style(){if(document.getElementById('presenceStyle'))return;const s=document.createElement('style');s.id='presenceStyle';s.textContent=`#chatPresence{display:block;font-size:12px;margin-top:2px;color:#6a756f}.presence-online{color:#0b7a53!important;font-weight:800}.presence-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#17a65b;margin-right:5px;vertical-align:1px}`;document.head.appendChild(s)}
async function ping(force=false){if(!uid)return;const now=Date.now();if(!force&&now-lastWrite<45000)return;lastWrite=now;try{await setDoc(doc(db,'presence',uid),{online:true,lastSeen:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true})}catch{}}
async function markAway(){if(!uid)return;try{await setDoc(doc(db,'presence',uid),{online:false,lastSeen:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true})}catch{}}
function fmt(ts){const d=ts?.toDate?.();if(!d)return 'Offline';const diff=Date.now()-d.getTime();if(diff<120000)return 'Visto há pouco';if(diff<86400000)return 'Visto por último às '+d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});return 'Visto por último em '+d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})+' às '+d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}
function ensure(){const email=document.getElementById('chatEmail');if(!email)return null;let el=document.getElementById('chatPresence');if(!el){el=document.createElement('small');el.id='chatPresence';email.insertAdjacentElement('afterend',el)}return el}
function watch(){if(stopWatch){stopWatch();stopWatch=null}const email=(document.getElementById('chatEmail')?.textContent||'').trim();const users=[...document.querySelectorAll('#usersList .user')];const row=users.find(x=>(x.querySelector('.user-email')?.textContent||'').trim()===email);const other=row?.dataset?.uid;if(!other)return;const el=ensure();if(!el)return;stopWatch=onSnapshot(doc(db,'presence',other),snap=>{const p=snap.data()||{},d=p.lastSeen?.toDate?.(),fresh=d&&Date.now()-d.getTime()<90000;if(p.online&&fresh){el.className='presence-online';el.innerHTML='<span class="presence-dot"></span>Online agora'}else{el.className='';el.textContent=fmt(p.lastSeen)}})}
function start(){style();onAuthStateChanged(auth,u=>{uid=u?.uid||'';clearInterval(timer);if(uid){ping(true);timer=setInterval(()=>{if(document.visibilityState==='visible')ping()},60000)}});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')ping(true);else markAway()});window.addEventListener('pagehide',markAway);document.addEventListener('click',e=>{if(e.target.closest('#usersList .user'))setTimeout(watch,250)});const head=document.querySelector('.chat-head');if(head)new MutationObserver(()=>setTimeout(watch,80)).observe(head,{subtree:true,childList:true,characterData:true});setInterval(()=>{if(document.getElementById('activeChat')&&!document.getElementById('activeChat').classList.contains('hidden'))watch()},60000)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();