import{getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import{getFirestore,doc,getDoc,setDoc,collection,query,where,limit,getDocs}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const cfg={apiKey:"AIzaSyCcAVkmLUKPcEMZ5erDswbOQ8eO493pl2I",authDomain:"chama-cfc28.firebaseapp.com",projectId:"chama-cfc28",storageBucket:"chama-cfc28.firebasestorage.app",messagingSenderId:"680045231088",appId:"1:680045231088:web:8db35684e4b56a320ebb35"};
const app=getApps()[0]||initializeApp(cfg),auth=getAuth(app),db=getFirestore(app);let me=null,myType="social";
const norm=v=>String(v||"").trim().toLowerCase();
function style(){if(document.getElementById("ptStyle"))return;const s=document.createElement("style");s.id="ptStyle";s.textContent=`.pt-badge{display:inline-flex;align-items:center;gap:5px;margin:5px 0;padding:5px 9px;border-radius:999px;background:#e8f5ef;color:#087650;font-size:12px;font-weight:800}.pt-choose{position:fixed;inset:0;background:#0009;z-index:300;display:grid;place-items:center;padding:16px}.pt-box{width:min(430px,100%);background:#fff;border-radius:22px;padding:20px}.pt-box h2{margin:0 0 6px;color:#087650}.pt-box p{color:#66736d;margin:0 0 15px}.pt-option{width:100%;text-align:left;border:1px solid #dfe7e3;background:#fff;border-radius:16px;padding:15px;margin:7px 0}.pt-option b{display:block;font-size:16px;color:#173f33}.pt-option span{display:block;font-size:13px;color:#65736d;margin-top:4px}.pt-option.prof{border-color:#0b8b61;background:#effaf5}.pt-change{border:0;background:#e8f5ef;color:#087650;border-radius:10px;padding:8px 10px;font-weight:800;margin-top:7px}`;document.head.appendChild(s)}
function setOwnCatalogVisible(){const btn=document.getElementById("chatCatalogBtn");if(btn)btn.style.display=myType==="profissional"?"":"none";const owner=document.getElementById("catalogOwnerActions");if(owner)owner.style.display=myType==="profissional"?"":"none"}
function chooser(required=false){document.getElementById("ptChooser")?.remove();const d=document.createElement("div");d.id="ptChooser";d.className="pt-choose";d.innerHTML=`<div class="pt-box"><h2>Como você vai usar o Chama?</h2><p>Você pode mudar depois no seu perfil.</p><button class="pt-option" data-t="social"><b>👤 Perfil Social</b><span>Para conversar, fazer amigos e compartilhar seu perfil. Não possui catálogo.</span></button><button class="pt-option prof" data-t="profissional"><b>💼 Perfil Profissional</b><span>Para negócios, vendedores e profissionais. Inclui catálogo de produtos.</span></button></div>`;document.body.appendChild(d);if(!required)d.onclick=e=>{if(e.target===d)d.remove()};d.querySelectorAll("[data-t]").forEach(b=>b.onclick=async()=>{if(!me)return;const tipo=b.dataset.t;try{b.disabled=true;await setDoc(doc(db,"users",me.uid),{tipoPerfil:tipo},{merge:true});myType=tipo;d.remove();setOwnCatalogVisible();await syncOpenProfile();alert(tipo==="profissional"?"Perfil Profissional ativado. Seu catálogo está disponível.":"Perfil Social ativado. O catálogo ficará oculto.")}catch(e){b.disabled=false;alert("Não consegui salvar o tipo de perfil.")}})}
async function getUserByEmail(email){if(!email)return null;try{const s=await getDocs(query(collection(db,"users"),where("email","==",email),limit(1)));let out=null;s.forEach(d=>out={uid:d.id,...d.data()});return out}catch{return null}}
function setProfileAvatar(u){const el=document.getElementById("profileAvatar");if(!el||!u)return;el.innerHTML="";if(u.foto){const img=document.createElement("img");img.src=u.foto;img.alt=u.nome||"Foto do perfil";img.style.width="100%";img.style.height="100%";img.style.objectFit="cover";img.style.display="block";el.appendChild(img)}else el.textContent=(u.nome||u.email||"U").trim().charAt(0).toUpperCase()||"U"}
async function syncOpenProfile(){const modal=document.getElementById("profileModal");if(!modal||modal.classList.contains("hidden"))return;const email=norm(document.getElementById("profileEmail")?.textContent);if(!email)return;const u=await getUserByEmail(email);if(!u)return;setProfileAvatar(u);document.getElementById("ptBadge")?.remove();document.getElementById("ptChange")?.remove();const hero=modal.querySelector(".profile-hero");if(hero){const badge=document.createElement("div");badge.id="ptBadge";badge.className="pt-badge";badge.textContent=u.tipoPerfil==="profissional"?"💼 Perfil Profissional":"👤 Perfil Social";hero.insertAdjacentElement("afterend",badge);if(me&&email===norm(me.email)){const btn=document.createElement("button");btn.id="ptChange";btn.className="pt-change";btn.textContent="Alterar tipo de perfil";btn.onclick=()=>chooser(false);badge.insertAdjacentElement("afterend",btn)}}const catalogBtn=[...document.querySelectorAll("#profileActions button")].find(b=>b.textContent.includes("Ver catálogo"));if(catalogBtn)catalogBtn.style.display=u.tipoPerfil==="profissional"?"":"none"}
function refreshSoon(){setTimeout(()=>{setOwnCatalogVisible();syncOpenProfile()},100)}
style();document.addEventListener("click",refreshSoon,true);onAuthStateChanged(auth,async u=>{me=u;if(!u){document.getElementById("ptBadge")?.remove();document.getElementById("ptChange")?.remove();return}try{const s=await getDoc(doc(db,"users",u.uid)),data=s.exists()?s.data():{};if(data.tipoPerfil==="social"||data.tipoPerfil==="profissional"){myType=data.tipoPerfil;setOwnCatalogVisible()}else{myType="social";setOwnCatalogVisible();setTimeout(()=>chooser(true),350)}}catch{}});
