import{getApps,getApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import{getFirestore,doc,getDoc,setDoc,collection,query,where,limit,getDocs,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const app=getApps().length?getApp():null;
if(app){
const auth=getAuth(app),db=getFirestore(app);let me=null;
const norm=v=>String(v||"").trim().toLowerCase();
function esc(v=""){return String(v).replace(/[&<>"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[s]))}
function css(){if(document.getElementById("proProfileStyle"))return;const s=document.createElement("style");s.id="proProfileStyle";s.textContent=`.pro-box{margin-top:14px;border:1px solid #e1e8e4;background:#f8fbf9;border-radius:16px;padding:14px}.pro-title{font-weight:850;color:#0b7a53;margin-bottom:10px}.pro-grid{display:grid;gap:9px}.pro-item{background:#fff;border-radius:12px;padding:10px 12px}.pro-label{font-size:11px;color:#6a756f;font-weight:800;text-transform:uppercase;margin-bottom:3px}.pro-value{font-size:14px;word-break:break-word}.pro-edit{position:fixed;inset:0;background:#0009;z-index:310;display:grid;place-items:center;padding:14px}.pro-card{width:min(470px,100%);max-height:92dvh;overflow:auto;background:#fff;border-radius:20px;padding:18px}.pro-card h3{margin:0 0 12px;color:#0b7a53}.pro-field{display:grid;gap:6px;margin:10px 0}.pro-field label{font-size:13px;font-weight:750}.pro-field input,.pro-field textarea{width:100%;border:1px solid #ccd6d1;border-radius:12px;padding:11px 12px;font:inherit}.pro-field textarea{min-height:90px;resize:vertical}.pro-actions{display:flex;gap:8px;margin-top:12px}.pro-actions button{flex:1;border:0;border-radius:12px;padding:12px;font-weight:800}.pro-save{background:#0b7a53;color:#fff}.pro-cancel{background:#edf3f0;color:#0b7a53}.pro-talk{background:#0b7a53!important;color:#fff!important}`;document.head.appendChild(s)}
async function userByOpenProfile(){const email=norm(document.getElementById("profileEmail")?.textContent);if(!email)return null;try{const s=await getDocs(query(collection(db,"users"),where("email","==",email),limit(1)));let out=null;s.forEach(d=>out={uid:d.id,...d.data()});return out}catch{return null}}
function infoHtml(u){return `<div id="proBox" class="pro-box"><div class="pro-title">💼 Informações profissionais</div><div class="pro-grid"><div class="pro-item"><div class="pro-label">Negócio / atividade</div><div class="pro-value">${esc(u.nomeNegocio||"Não informado")}</div></div><div class="pro-item"><div class="pro-label">Categoria</div><div class="pro-value">${esc(u.categoriaProfissional||"Não informada")}</div></div><div class="pro-item"><div class="pro-label">Cidade / região</div><div class="pro-value">${esc(u.cidadeProfissional||"Não informada")}</div></div><div class="pro-item"><div class="pro-label">Horário de atendimento</div><div class="pro-value">${esc(u.horarioAtendimento||"Não informado")}</div></div><div class="pro-item"><div class="pro-label">Apresentação comercial</div><div class="pro-value">${esc(u.descricaoComercial||"Sem apresentação comercial.")}</div></div></div></div>`}
function openChatFromProfile(email){document.getElementById("profileModal")?.classList.add("hidden");const target=norm(email);const rows=[...document.querySelectorAll("#usersList .user")];const row=rows.find(r=>norm(r.querySelector(".user-email")?.textContent)===target);if(row)row.click();else alert("Abra este usuário pela lista de pessoas para iniciar a conversa.")}
function editor(u){document.getElementById("proEditor")?.remove();const d=document.createElement("div");d.id="proEditor";d.className="pro-edit";d.innerHTML=`<div class="pro-card"><h3>💼 Meu Perfil Profissional</h3><div class="pro-field"><label>Nome do negócio ou atividade</label><input id="proNome" maxlength="100" value="${esc(u.nomeNegocio||"")}" placeholder="Ex.: Loja Bananal"></div><div class="pro-field"><label>Categoria / profissão</label><input id="proCategoria" maxlength="80" value="${esc(u.categoriaProfissional||"")}" placeholder="Ex.: Moda, eletricista, manicure"></div><div class="pro-field"><label>Cidade / região</label><input id="proCidade" maxlength="100" value="${esc(u.cidadeProfissional||"")}" placeholder="Ex.: São Paulo - Zona Leste"></div><div class="pro-field"><label>Horário de atendimento</label><input id="proHorario" maxlength="120" value="${esc(u.horarioAtendimento||"")}" placeholder="Ex.: Seg a Sex, 9h às 18h"></div><div class="pro-field"><label>Apresentação comercial</label><textarea id="proDesc" maxlength="600" placeholder="Conte o que você vende ou qual serviço presta.">${esc(u.descricaoComercial||"")}</textarea></div><div class="pro-actions"><button class="pro-cancel" type="button">Cancelar</button><button class="pro-save" type="button">Salvar</button></div></div>`;document.body.appendChild(d);d.querySelector(".pro-cancel").onclick=()=>d.remove();d.onclick=e=>{if(e.target===d)d.remove()};d.querySelector(".pro-save").onclick=async()=>{const b=d.querySelector(".pro-save");b.disabled=true;b.textContent="Salvando...";try{await setDoc(doc(db,"users",me.uid),{nomeNegocio:d.querySelector("#proNome").value.trim(),categoriaProfissional:d.querySelector("#proCategoria").value.trim(),cidadeProfissional:d.querySelector("#proCidade").value.trim(),horarioAtendimento:d.querySelector("#proHorario").value.trim(),descricaoComercial:d.querySelector("#proDesc").value.trim(),updatedAt:serverTimestamp()},{merge:true});d.remove();setTimeout(sync,120)}catch(e){b.disabled=false;b.textContent="Salvar";alert("Não consegui salvar os dados profissionais.")}}}
async function sync(){const modal=document.getElementById("profileModal"),view=document.getElementById("profileView");if(!modal||!view||modal.classList.contains("hidden"))return;document.getElementById("proBox")?.remove();document.getElementById("proEditBtn")?.remove();document.getElementById("proTalkBtn")?.remove();const u=await userByOpenProfile();if(!u||u.tipoPerfil!=="profissional")return;const info=view.querySelector(".profile-info");if(info)info.insertAdjacentHTML("afterend",infoHtml(u));const actions=document.getElementById("profileActions");if(!actions)return;const mine=!!(me&&norm(u.email)===norm(me.email));if(mine){const b=document.createElement("button");b.id="proEditBtn";b.className="secondary";b.textContent="💼 Editar dados profissionais";b.onclick=()=>editor(u);actions.appendChild(b)}else{const b=document.createElement("button");b.id="proTalkBtn";b.className="secondary pro-talk";b.textContent="💬 Falar agora";b.onclick=()=>openChatFromProfile(u.email);actions.prepend(b)}}
function start(){css();document.addEventListener("click",()=>setTimeout(sync,140),true);onAuthStateChanged(auth,u=>{me=u||null})}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",start):start();
}
