import{getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import{getFirestore,doc,getDoc,setDoc,collection,query,where,getDocs,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const cfg={apiKey:"AIzaSyCcAVkmLUKPcEMZ5erDswbOQ8eO493pl2I",authDomain:"chama-cfc28.firebaseapp.com",projectId:"chama-cfc28",storageBucket:"chama-cfc28.firebasestorage.app",messagingSenderId:"680045231088",appId:"1:680045231088:web:8db35684e4b56a320ebb35"};
const app=getApps()[0]||initializeApp(cfg),auth=getAuth(app),db=getFirestore(app);let me=null,count=0;
const BASE="https://chama.alibr.com.br/";
const norm=v=>String(v||"").trim().toLowerCase();
const incoming=new URL(location.href).searchParams.get("ref");if(incoming)try{localStorage.setItem("chama_ref",incoming)}catch{}
function style(){if(document.getElementById("refStyle"))return;const s=document.createElement("style");s.id="refStyle";s.textContent=`.ref-btn{width:100%;border:1px solid #c9d4cf;background:#fff;color:#0b7a53;padding:13px 16px;border-radius:14px;font-weight:800;cursor:pointer}.ref-count{text-align:center;color:#6a756f;font-size:12px;margin-top:-2px;margin-bottom:4px}.chama-share-main{position:fixed;right:10px;top:50%;transform:translateY(-50%);z-index:180;width:58px;min-height:58px;border:0;border-radius:18px;background:#0b7a53;color:#fff;box-shadow:0 8px 24px #0003;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;padding:8px 5px;font-weight:900;cursor:pointer}.chama-share-main .share-icon{font-size:22px;line-height:1}.chama-share-main .share-word{font-size:9px;line-height:1.05;text-align:center}.chama-share-main:active{transform:translateY(-50%) scale(.96)}@media(max-width:700px){.chama-share-main{right:8px;top:auto;bottom:92px;transform:none;width:54px;min-height:54px;border-radius:17px}.chama-share-main:active{transform:scale(.96)}}`;document.head.appendChild(s)}
function link(){return `${BASE}?perfil=${encodeURIComponent(me.uid)}&ref=${encodeURIComponent(me.uid)}`}
async function registerReferral(){let ref="";try{ref=localStorage.getItem("chama_ref")||""}catch{}if(!me||!ref||ref===me.uid)return;try{const mine=await getDoc(doc(db,"users",me.uid));if(mine.exists()&&mine.data().indicadoPor){localStorage.removeItem("chama_ref");return}const inviter=await getDoc(doc(db,"users",ref));if(!inviter.exists()){localStorage.removeItem("chama_ref");return}await setDoc(doc(db,"users",me.uid),{indicadoPor:ref,indicadoEm:serverTimestamp()},{merge:true});localStorage.removeItem("chama_ref")}catch{}}
async function loadCount(){if(!me)return;try{const s=await getDocs(query(collection(db,"users"),where("indicadoPor","==",me.uid)));count=s.size}catch{count=0}refreshOwnProfile()}
async function shareReferral(){if(!me)return;const url=link(),text="Compartilhe o Chama com seus amigos e cresça junto com o aplicativo. 🔥🇧🇷\nEste é o meu perfil no Chama:";try{if(navigator.share){await navigator.share({title:"Chama",text,url});return}await navigator.clipboard.writeText(`${text}\n${url}`);alert("Seu link do Chama foi copiado!")}catch{try{await navigator.clipboard.writeText(`${text}\n${url}`);alert("Seu link do Chama foi copiado!")}catch{prompt("Copie seu link do Chama:",url)}}}
function installMainShare(){let b=document.getElementById('chamaShareMain');if(!me){b?.remove();return}if(b)return;b=document.createElement('button');b.id='chamaShareMain';b.className='chama-share-main';b.type='button';b.title='Compartilhe o Chama com seus amigos';b.setAttribute('aria-label','Compartilhar meu perfil e convite do Chama');b.innerHTML='<span class="share-icon">↗</span><span class="share-word">Compartilhar</span>';b.onclick=shareReferral;document.body.appendChild(b)}
function refreshOwnProfile(){const modal=document.getElementById("profileModal"),actions=document.getElementById("profileActions");if(!me||!modal||modal.classList.contains("hidden")||!actions)return;const email=norm(document.getElementById("profileEmail")?.textContent);if(email!==norm(me.email)){document.getElementById("refBtn")?.remove();document.getElementById("refCount")?.remove();return}let btn=document.getElementById("refBtn");if(!btn){btn=document.createElement("button");btn.id="refBtn";btn.className="ref-btn";btn.textContent="🎁 Compartilhar meu Chama";btn.onclick=shareReferral;actions.appendChild(btn)}let c=document.getElementById("refCount");if(!c){c=document.createElement("div");c.id="refCount";c.className="ref-count";btn.insertAdjacentElement("afterend",c)}c.textContent=count===1?"1 pessoa entrou pelo seu convite":`${count} pessoas entraram pelo seu convite`}
style();document.addEventListener("click",()=>setTimeout(refreshOwnProfile,120),true);onAuthStateChanged(auth,async u=>{me=u||null;if(!u){document.getElementById('chamaShareMain')?.remove();return}installMainShare();await registerReferral();await loadCount()});
