import{initializeApp,getApps}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getFirestore,collection,query,where,limit,getDocs}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const CHATSHOP_CONFIG={apiKey:"AIzaSyBZlCM-6l_iV_GTirvTwUumKM3ZGRvgxt8",authDomain:"chatshop-97ea3.firebaseapp.com",projectId:"chatshop-97ea3",storageBucket:"chatshop-97ea3.firebasestorage.app",messagingSenderId:"430779427610",appId:"1:430779427610:web:7418f6e4f6006535209aa3"};
const $=(s,r)=>(r||document).querySelector(s);
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function app(){let a=getApps().find(x=>x.name==='shopads-chama-feed');if(!a)a=initializeApp(CHATSHOP_CONFIG,'shopads-chama-feed');return a}
function styles(){if($('#chamaAdsFeedStyles'))return;const s=document.createElement('style');s.id='chamaAdsFeedStyles';s.textContent=`#chamaAdsBtn{white-space:nowrap}.cad-overlay{position:fixed;inset:0;z-index:11950;background:#f4f5f4;display:none;overflow:auto}.cad-overlay.open{display:block}.cad-top{position:sticky;top:0;z-index:2;background:#0b7a53;color:#fff;padding:14px 16px}.cad-head{max-width:720px;margin:auto;display:flex;align-items:center;gap:10px}.cad-head h2{margin:0;flex:1}.cad-close{border:0;background:#ffffff20;color:#fff;width:40px;height:40px;border-radius:50%;font-size:20px}.cad-body{max-width:720px;margin:auto;padding:14px}.cad-note{background:#fff;border:1px solid #dde5e1;border-radius:14px;padding:12px;color:#66756e;font-size:13px;margin-bottom:12px}.cad-card{background:#fff;border:1px solid #e4e8e6;border-radius:16px;padding:14px;margin-bottom:12px;box-shadow:0 4px 16px #0000000b}.cad-row{display:flex;gap:12px;align-items:flex-start}.cad-img{width:88px;height:88px;border-radius:12px;object-fit:cover;background:#f1f3f2}.cad-grow{flex:1;min-width:0}.cad-title{font-weight:900;font-size:16px;margin-bottom:5px}.cad-desc{font-size:13px;color:#66756e;line-height:1.4}.cad-badge{display:inline-block;margin-top:7px;background:#f3e8ff;color:#6b21a8;border-radius:999px;padding:5px 8px;font-size:10px;font-weight:900}.cad-go{width:100%;margin-top:11px;border:0;border-radius:11px;padding:12px;background:#6d28d9;color:#fff;font-weight:900}.cad-empty{text-align:center;padding:40px 18px;color:#66756e}@media(max-width:520px){#chamaAdsBtn{padding:9px 10px}.cad-img{width:76px;height:76px}}`;document.head.appendChild(s)}
async function load(){const box=$('#chamaAdsList');if(!box)return;box.innerHTML='<div class="cad-empty">Carregando anúncios...</div>';try{const db=getFirestore(app()),q=query(collection(db,'shopadsCampaigns'),where('status','==','teste'),limit(20)),snap=await getDocs(q),items=[];snap.forEach(d=>items.push({id:d.id,...d.data()}));if(!items.length){box.innerHTML='<div class="cad-empty">Ainda não há campanhas disponíveis.</div>';return}box.innerHTML=items.map(c=>`<article class="cad-card"><div class="cad-row">${c.image?`<img class="cad-img" src="${esc(c.image)}" alt="">`:'<div class="cad-img"></div>'}<div class="cad-grow"><div class="cad-title">${esc(c.title||'Anúncio')}</div><div class="cad-desc">${esc(c.description||'')}</div><span class="cad-badge">Patrocinado · Shop Ads</span></div></div><button class="cad-go" data-campaign="${esc(c.id)}">Ver oferta</button></article>`).join('');box.onclick=e=>{const b=e.target.closest('[data-campaign]');if(!b)return;const url='https://alibr.com.br/shopads-go.html?c='+encodeURIComponent(b.dataset.campaign)+'&source=chama';window.open(url,'_blank','noopener')}}catch(e){console.warn('ShopAds feed:',e);box.innerHTML='<div class="cad-empty">Não foi possível carregar os anúncios agora.</div>'}}
function openFeed(){styles();let o=$('#chamaAdsOverlay');if(!o){o=document.createElement('div');o.id='chamaAdsOverlay';o.className='cad-overlay';o.innerHTML='<div class="cad-top"><div class="cad-head"><h2>📣 Anúncios</h2><button class="cad-close" type="button">×</button></div></div><main class="cad-body"><div class="cad-note">Campanhas do Shop Ads. Os anúncios são carregados somente quando você abre esta área.</div><div id="chamaAdsList"></div></main>';document.body.appendChild(o);$('.cad-close',o).onclick=()=>o.classList.remove('open')}o.classList.add('open');load()}
function install(){styles();const top=$('.topbar');if(!top||$('#chamaAdsBtn'))return;const boost=$('#chamaShopAdsBtn'),logout=$('#logoutBtn');const b=document.createElement('button');b.id='chamaAdsBtn';b.type='button';b.className='iconbtn';b.textContent='📣 Anúncios';b.title='Ver anúncios do Shop Ads';b.onclick=openFeed;if(boost)top.insertBefore(b,boost);else if(logout)top.insertBefore(b,logout);else top.appendChild(b)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});window.ChamaAds={open:openFeed,reload:load};
