/* Chama -> ShopAds bridge. Isolado: não altera mensagens, chamadas, mídia ou Firestore. */
(function(){
'use strict';
const SHOPADS_URL='https://alibr.com.br/shopads-chama.html';
const BUDGETS=[5,10,15,20,30,50];
const DRAFT_KEY='chama_shopads_draft_v1';
const $=(s,r)=>(r||document).querySelector(s);
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ensureStyles(){if($('#chamaShopAdsStyles'))return;const s=document.createElement('style');s.id='chamaShopAdsStyles';s.textContent=`
#chamaShopAdsBtn{white-space:nowrap}.csa-overlay{position:fixed;inset:0;z-index:12000;background:#0008;display:none;align-items:flex-end;justify-content:center;padding:0}.csa-overlay.open{display:flex}.csa-sheet{width:min(620px,100%);max-height:92dvh;overflow:auto;background:#fff;border-radius:22px 22px 0 0;padding:18px;color:#14221c;box-shadow:0 -12px 40px #0003}.csa-head{display:flex;align-items:center;gap:10px}.csa-head h2{margin:0;flex:1}.csa-close{border:0;background:#eef2ef;width:38px;height:38px;border-radius:50%;font-size:20px}.csa-note{background:#f7f5ff;border:1px solid #e8ddff;color:#5b21b6;padding:10px 12px;border-radius:12px;font-size:13px;margin:12px 0}.csa-field{display:grid;gap:6px;margin:12px 0}.csa-field label{font-size:13px;font-weight:800}.csa-field input,.csa-field select{width:100%;padding:12px;border:1px solid #d6ddd9;border-radius:12px;outline:none}.csa-budgets{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.csa-budget{border:1px solid #d6ddd9;background:#fff;border-radius:12px;padding:12px;font-weight:900}.csa-budget.active{background:#0b7a53;color:#fff;border-color:#0b7a53}.csa-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:16px}.csa-actions button{border:0;border-radius:12px;padding:13px;font-weight:900}.csa-save{background:#eef4f1;color:#0b7a53}.csa-go{background:#6d28d9;color:#fff}@media(max-width:520px){#chamaShopAdsBtn{padding:9px 10px}.csa-actions{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function loadDraft(){try{return JSON.parse(localStorage.getItem(DRAFT_KEY)||'{}')}catch{return{}}}
function saveDraft(v){try{localStorage.setItem(DRAFT_KEY,JSON.stringify(v))}catch{}}
function buildUrl(d){const u=new URL(SHOPADS_URL);u.searchParams.set('source','chama');u.searchParams.set('type',d.type||'catalogo');u.searchParams.set('budget',String(d.budget||5));if(d.title)u.searchParams.set('title',d.title);if(d.url)u.searchParams.set('url',d.url);return u.toString()}
function openSheet(){ensureStyles();let o=$('#chamaShopAdsOverlay');if(!o){o=document.createElement('div');o.id='chamaShopAdsOverlay';o.className='csa-overlay';document.body.appendChild(o)}const d=loadDraft(),budget=BUDGETS.includes(Number(d.budget))?Number(d.budget):5;o.innerHTML=`<section class="csa-sheet" role="dialog" aria-modal="true" aria-label="Impulsionar no Shop Ads"><div class="csa-head"><h2>🚀 Impulsionar no Chama</h2><button class="csa-close" type="button">×</button></div><div class="csa-note"><b>Fase de teste:</b> nenhum valor será cobrado agora. O Chama prepara a campanha e envia para o núcleo Shop Ads.</div><div class="csa-field"><label>O que deseja impulsionar?</label><select id="csaType"><option value="catalogo">Catálogo</option><option value="produto">Produto</option><option value="anuncio">Anúncio</option><option value="perfil">Perfil/loja</option></select></div><div class="csa-field"><label>Nome da campanha</label><input id="csaTitle" maxlength="120" placeholder="Ex.: Catálogo de ofertas" value="${esc(d.title||'')}"></div><div class="csa-field"><label>Link do catálogo, produto ou página</label><input id="csaUrl" type="url" inputmode="url" placeholder="https://..." value="${esc(d.url||'')}"></div><div class="csa-field"><label>Orçamento do impulsionamento</label><div class="csa-budgets">${BUDGETS.map(v=>`<button type="button" class="csa-budget ${v===budget?'active':''}" data-budget="${v}">R$ ${v}</button>`).join('')}</div></div><div class="csa-actions"><button type="button" class="csa-save">Salvar rascunho</button><button type="button" class="csa-go">Continuar no Shop Ads</button></div></section>`;o.classList.add('open');$('#csaType',o).value=d.type||'catalogo';let selected=budget;o.onclick=e=>{if(e.target===o||e.target.closest('.csa-close')){o.classList.remove('open');return}const b=e.target.closest('[data-budget]');if(b){selected=Number(b.dataset.budget);o.querySelectorAll('.csa-budget').forEach(x=>x.classList.toggle('active',x===b));return}if(e.target.closest('.csa-save')){const next={type:$('#csaType',o).value,title:$('#csaTitle',o).value.trim(),url:$('#csaUrl',o).value.trim(),budget:selected,source:'chama',updatedAt:new Date().toISOString()};saveDraft(next);e.target.closest('.csa-save').textContent='Salvo ✓';setTimeout(()=>{const x=$('.csa-save',o);if(x)x.textContent='Salvar rascunho'},1200);return}if(e.target.closest('.csa-go')){const next={type:$('#csaType',o).value,title:$('#csaTitle',o).value.trim(),url:$('#csaUrl',o).value.trim(),budget:selected,source:'chama',updatedAt:new Date().toISOString()};if(next.url&&!/^https?:\/\//i.test(next.url)){alert('Digite um link completo começando com http:// ou https://');return}saveDraft(next);window.open(buildUrl(next),'_blank','noopener')}}}
function install(){ensureStyles();const top=$('.topbar');if(!top||$('#chamaShopAdsBtn'))return;const logout=$('#logoutBtn');const b=document.createElement('button');b.id='chamaShopAdsBtn';b.type='button';b.className='iconbtn';b.textContent='🚀 Impulsionar';b.title='Impulsionar catálogo, produto ou anúncio';b.onclick=openSheet;if(logout)top.insertBefore(b,logout);else top.appendChild(b)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});
window.ChamaShopAds={open:openSheet,loadDraft};
})();