(()=>{
  const STYLE_ID='chamaTargetedBannerStyleV1';
  let me=null,db=null,fs=null;
  const esc=v=>String(v||'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
  const safeUrl=v=>{try{const u=new URL(String(v||'').trim());return u.protocol==='https:'?u.href:''}catch{return ''}};
  function style(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`.chama-targeted-banner{margin:9px 18px;border:1px solid #e5d08e;background:#fff8dd;border-radius:16px;overflow:hidden;box-shadow:0 3px 12px #49390010;display:grid;grid-template-columns:104px minmax(0,1fr);min-height:104px}.chama-targeted-banner:not(:has(img)){grid-template-columns:1fr;min-height:0}.chama-targeted-banner img{display:block;width:104px;height:104px;object-fit:contain;background:#fff}.chama-targeted-banner-body{padding:9px 11px;display:flex;align-items:center;gap:8px;min-width:0}.chama-targeted-banner-copy{flex:1;min-width:0}.chama-targeted-banner-copy small{display:block;color:#966000;font-size:10px;font-weight:900}.chama-targeted-banner-copy strong{display:-webkit-box;color:#392f16;font-size:14px;line-height:1.25;margin-top:3px;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.chama-targeted-banner a{background:#0b7a53;color:#fff;text-decoration:none;border-radius:9px;padding:8px 9px;font-size:12px;font-weight:900;white-space:nowrap}@media(max-width:420px){.chama-targeted-banner{margin:8px 12px;grid-template-columns:92px minmax(0,1fr);min-height:92px}.chama-targeted-banner img{width:92px;height:92px}.chama-targeted-banner-body{padding:8px;align-items:stretch;flex-direction:column;gap:5px}.chama-targeted-banner a{text-align:center;padding:7px 8px}.chama-targeted-banner-copy strong{font-size:13px}}`;document.head.appendChild(s)}
  function remove(){document.getElementById('chamaTargetedBanner')?.remove();delete document.body.dataset.affiliateDayAllowed}
  function placeCustom(b){document.getElementById('chamaTargetedBanner')?.remove();const image=safeUrl(b.image),link=safeUrl(b.link);if(!image&&!b.title)return;const box=document.createElement('section');box.id='chamaTargetedBanner';box.className='chama-targeted-banner';box.innerHTML=`${image?`<img src="${esc(image)}" alt="Banner selecionado pelo Chama" loading="lazy">`:''}<div class="chama-targeted-banner-body"><div class="chama-targeted-banner-copy"><small>📢 PARA VOCÊ</small><strong>${esc(b.title||'Novidade no Chama')}</strong></div>${link?`<a href="${esc(link)}" target="_blank" rel="noopener noreferrer sponsored">${esc(b.buttonText||'Ver agora')}</a>`:''}</div>`;const quick=document.getElementById('chamaQuickMenu'),side=document.querySelector('.sidebar');if(quick)quick.insertAdjacentElement('beforebegin',box);else if(side)side.prepend(box);else return;}
  async function apply(){remove();if(!me||!db||!fs)return;try{const s=await fs.getDoc(fs.doc(db,'users',me.uid)),b=s.data()?.adminBanner||{};if(!b.enabled)return;if(b.kind==='affiliateDay'){document.body.dataset.affiliateDayAllowed='true';document.dispatchEvent(new CustomEvent('chama-targeted-banner-ready'));return}placeCustom(b)}catch(e){console.warn('Chama: banner individual não carregou',e)}}
  async function start(attempt=0){style();try{const appMod=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js'),app=appMod.getApps()[0];if(!app){if(attempt<30)setTimeout(()=>start(attempt+1),150);return}const authMod=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js');fs=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js');db=fs.getFirestore(app);authMod.onAuthStateChanged(authMod.getAuth(app),u=>{me=u||null;apply()});new MutationObserver(()=>{if(me&&!document.getElementById('chamaTargetedBanner'))apply()}).observe(document.body,{childList:true,subtree:false})}catch(e){console.warn(e)}}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>start(),{once:true}):start();
})();
