(()=>{
  const STYLE_ID='chamaTargetedBannerStyleV1';
  let me=null,db=null,fs=null;
  const esc=v=>String(v||'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
  const safeUrl=v=>{try{const u=new URL(String(v||'').trim());return u.protocol==='https:'?u.href:''}catch{return ''}};
  function style(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`.chama-targeted-banner{margin:10px 18px;border:1px solid #e5d08e;background:#fff8dd;border-radius:18px;overflow:hidden;box-shadow:0 4px 16px #49390012}.chama-targeted-banner img{display:block;width:100%;max-height:190px;object-fit:cover;background:#eee}.chama-targeted-banner-body{padding:12px 14px;display:flex;align-items:center;gap:10px}.chama-targeted-banner-copy{flex:1;min-width:0}.chama-targeted-banner-copy small{display:block;color:#966000;font-weight:900}.chama-targeted-banner-copy strong{display:block;color:#392f16;margin-top:3px}.chama-targeted-banner a{background:#0b7a53;color:#fff;text-decoration:none;border-radius:11px;padding:10px 12px;font-weight:900;white-space:nowrap}@media(max-width:420px){.chama-targeted-banner{margin:9px 12px}.chama-targeted-banner-body{align-items:stretch;flex-direction:column}.chama-targeted-banner a{text-align:center}}`;document.head.appendChild(s)}
  function remove(){document.getElementById('chamaTargetedBanner')?.remove();delete document.body.dataset.affiliateDayAllowed}
  function placeCustom(b){document.getElementById('chamaTargetedBanner')?.remove();const image=safeUrl(b.image),link=safeUrl(b.link);if(!image&&!b.title)return;const box=document.createElement('section');box.id='chamaTargetedBanner';box.className='chama-targeted-banner';box.innerHTML=`${image?`<img src="${esc(image)}" alt="Banner selecionado pelo Chama" loading="lazy">`:''}<div class="chama-targeted-banner-body"><div class="chama-targeted-banner-copy"><small>📢 PARA VOCÊ</small><strong>${esc(b.title||'Novidade no Chama')}</strong></div>${link?`<a href="${esc(link)}" target="_blank" rel="noopener noreferrer sponsored">${esc(b.buttonText||'Ver agora')}</a>`:''}</div>`;const quick=document.getElementById('chamaQuickMenu'),side=document.querySelector('.sidebar');if(quick)quick.insertAdjacentElement('beforebegin',box);else if(side)side.prepend(box);else return;}
  async function apply(){remove();if(!me||!db||!fs)return;try{const s=await fs.getDoc(fs.doc(db,'users',me.uid)),b=s.data()?.adminBanner||{};if(!b.enabled)return;if(b.kind==='affiliateDay'){document.body.dataset.affiliateDayAllowed='true';document.dispatchEvent(new CustomEvent('chama-targeted-banner-ready'));return}placeCustom(b)}catch(e){console.warn('Chama: banner individual não carregou',e)}}
  async function start(attempt=0){style();try{const appMod=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js'),app=appMod.getApps()[0];if(!app){if(attempt<30)setTimeout(()=>start(attempt+1),150);return}const authMod=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js');fs=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js');db=fs.getFirestore(app);authMod.onAuthStateChanged(authMod.getAuth(app),u=>{me=u||null;apply()});new MutationObserver(()=>{if(me&&!document.getElementById('chamaTargetedBanner'))apply()}).observe(document.body,{childList:true,subtree:false})}catch(e){console.warn(e)}}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>start(),{once:true}):start();
})();
