(()=>{
const STYLE='chamaTopbarMenuV2Style',MENU='chamaMainMenu',OWNER_UID='0Mhnp79AYQTLwH6vfpAKROSGBtU2';let adminReady=false,adminAllowed=false;
function styles(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`#logoutBtn{display:none!important}#adminBtn{display:none!important}.chama-main-menu-btn{border:1px solid #ffffff30;background:#ffffff18;color:#fff;border-radius:12px;padding:10px 13px;font-weight:900;font-size:22px;line-height:1;cursor:pointer;min-width:44px;height:44px}.chama-main-menu-backdrop{position:fixed;inset:0;background:#0005;z-index:7000}.chama-main-menu{position:fixed;top:0;right:0;width:min(330px,88vw);height:100dvh;background:#fff;z-index:7001;box-shadow:-12px 0 40px #0003;display:flex;flex-direction:column}.chama-menu-head{padding:18px 16px;border-bottom:1px solid #e6ebe8;display:flex;align-items:center;gap:10px}.chama-menu-head strong{font-size:18px;flex:1;color:#17372b}.chama-menu-close{border:0;background:#eef4f1;color:#0b7a53;border-radius:10px;padding:8px 11px;font-size:18px;cursor:pointer}.chama-menu-links{padding:12px;display:flex;flex-direction:column;gap:7px;overflow:auto}.chama-menu-link{display:flex;align-items:center;gap:12px;width:100%;border:1px solid #e0e7e3;background:#fff;color:#20382f;border-radius:13px;padding:13px 14px;text-align:left;font-weight:800;text-decoration:none;cursor:pointer}.chama-menu-link:active{background:#eef7f2}.chama-menu-icon{width:25px;text-align:center;font-size:18px}.chama-menu-spacer{flex:1;min-height:18px}.chama-menu-logout{color:#b42318;border-color:#f0d7d4;background:#fffafa}`;document.head.appendChild(s)}
function close(){document.getElementById(MENU)?.remove();document.getElementById('chamaMainMenuBackdrop')?.remove()}
function item(panel,icon,text,fn,cls=''){const b=document.createElement('button');b.type='button';b.className='chama-menu-link '+cls;b.innerHTML=`<span class="chama-menu-icon">${icon}</span><span>${text}</span>`;b.onclick=()=>{close();fn()};panel.appendChild(b);return b}
function renderAdmin(){const p=document.querySelector('#chamaMainMenu .chama-menu-links');if(!p||!adminReady||!adminAllowed||p.querySelector('[data-admin-menu]'))return;const spacer=p.querySelector('.chama-menu-spacer');const b=item(p,'🛡️','Admin',()=>location.href='./admin.html');b.setAttribute('data-admin-menu','1');if(spacer)p.insertBefore(b,spacer)}
async function resolveAdmin(){try{const {getApps}=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js');const {getAuth,onAuthStateChanged}=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js');const {getFirestore,doc,getDoc}=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js');const app=getApps()[0];if(!app)return;onAuthStateChanged(getAuth(app),async u=>{adminReady=true;adminAllowed=false;if(u){if(u.uid===OWNER_UID)adminAllowed=true;else{try{const s=await getDoc(doc(getFirestore(app),'users',u.uid));adminAllowed=s.exists()&&s.data()?.admin===true}catch{}}}renderAdmin()})}catch{adminReady=true;adminAllowed=false}}
function open(){if(document.getElementById(MENU))return;const back=document.createElement('div');back.id='chamaMainMenuBackdrop';back.className='chama-main-menu-backdrop';back.onclick=close;document.body.appendChild(back);const m=document.createElement('aside');m.id=MENU;m.className='chama-main-menu';m.innerHTML='<div class="chama-menu-head"><strong>Menu do Chama</strong><button type="button" class="chama-menu-close" aria-label="Fechar">×</button></div><div class="chama-menu-links"></div>';document.body.appendChild(m);m.querySelector('.chama-menu-close').onclick=close;const p=m.querySelector('.chama-menu-links');item(p,'📖','Como usar o Chama',()=>location.href='./como-usar.html');item(p,'🔒','Política de privacidade',()=>location.href='./politica-de-privacidade.html');const spacer=document.createElement('div');spacer.className='chama-menu-spacer';p.appendChild(spacer);const logout=document.getElementById('logoutBtn');if(logout)item(p,'🚪','Sair',()=>logout.click(),'chama-menu-logout');renderAdmin()}
function install(){const top=document.querySelector('.topbar');if(!top)return;styles();let b=document.getElementById('chamaMainMenuBtn');const old=document.getElementById('logoutBtn');if(!b){b=document.createElement('button');b.id='chamaMainMenuBtn';b.className='chama-main-menu-btn';b.type='button';b.title='Abrir menu';b.setAttribute('aria-label','Abrir menu');b.textContent='☰';if(old&&old.parentNode===top)top.insertBefore(b,old);else top.appendChild(b)}b.onclick=open;if(old)old.style.setProperty('display','none','important');const admin=document.getElementById('adminBtn');if(admin)admin.style.display='none'}
function start(){install();const top=document.querySelector('.topbar');if(top)new MutationObserver(install).observe(top,{childList:true,subtree:true});setInterval(install,1000);resolveAdmin();const v=document.createElement('script');v.src='./chama-visual-fixes.js?v=2';v.defer=true;document.head.appendChild(v);const m=document.createElement('script');m.src='./chama-message-media-runtime-v2.js?v=1';m.defer=true;document.head.appendChild(m)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();

let chamaViewportBase=0;
function keyboardFix(){const chat=document.getElementById('chatPanel'),active=document.getElementById('activeChat');if(!chat||!window.visualViewport)return;if(window.innerWidth>700){chat.style.top='';chat.style.right='';chat.style.bottom='';chat.style.left='';chat.style.height='';active?.style.removeProperty('height');active?.style.removeProperty('min-height');active?.style.removeProperty('overflow');const composer=document.getElementById('composer');if(composer){composer.style.position='';composer.style.bottom='';composer.style.zIndex=''}document.documentElement.style.removeProperty('--chama-keyboard-bottom');chamaViewportBase=Math.max(chamaViewportBase,window.innerHeight||document.documentElement.clientHeight||window.visualViewport.height);return}
const vv=window.visualViewport;
const current=Math.max(window.innerHeight||0,document.documentElement.clientHeight||0,vv.height||0);
if(!chamaViewportBase||vv.height>chamaViewportBase-80)chamaViewportBase=current;
const keyboard=Math.max(0,Math.round(chamaViewportBase-vv.height-vv.offsetTop));
chat.style.position='fixed';chat.style.top='66px';chat.style.right='0';chat.style.left='0';chat.style.bottom=keyboard+'px';chat.style.height='auto';
if(active){active.style.height='100%';active.style.minHeight='0';active.style.maxHeight='none';active.style.overflow='hidden'}
const messages=document.getElementById('messages');if(messages){messages.style.minHeight='0';messages.style.overflowY='auto';messages.style.overscrollBehavior='contain';}
const composer=document.getElementById('composer');if(composer){composer.style.position='sticky';composer.style.bottom='0';composer.style.zIndex='20';composer.style.flexShrink='0';}
document.documentElement.style.setProperty('--chama-keyboard-bottom',keyboard+'px');
}
function startKeyboardFix(){setTimeout(keyboardFix,50);window.visualViewport?.addEventListener('resize',keyboardFix,{passive:true});window.visualViewport?.addEventListener('scroll',keyboardFix,{passive:true});window.addEventListener('resize',keyboardFix,{passive:true});document.addEventListener('focusin',e=>{if(e.target?.id==='messageInput')setTimeout(keyboardFix,80)});document.addEventListener('focusout',e=>{if(e.target?.id==='messageInput')setTimeout(keyboardFix,120)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startKeyboardFix,{once:true});else startKeyboardFix();
})();
