(()=>{
  const STYLE_ID='chamaUnreadStyleV7';
  let meUid='',db=null,fs=null,stopChats=null;
  const chats=new Map();
  function style(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`#usersList .user{position:relative}#usersList .user.has-unread .user-name{color:#0b7a53;font-weight:900}.chama-conversation-side{margin-left:auto;display:grid;justify-items:end;gap:5px;flex:0 0 auto;min-width:38px}.chama-unread-badge{min-width:23px;height:23px;padding:0 7px;border-radius:999px;background:#18a566;color:#fff;display:grid;place-items:center;font-size:12px;font-weight:900;line-height:1;box-shadow:0 1px 2px #0002}.chama-last-message{font-size:11px;color:#7a8580;max-width:105px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#usersList .user.has-unread .chama-last-message{color:#0b7a53;font-weight:800}`;document.head.appendChild(s)}
  function render(){document.querySelectorAll('#usersList .user').forEach(row=>{const uid=row.dataset.uid;if(!uid)return;row.querySelector('.chama-conversation-side')?.remove();row.classList.remove('has-unread','chama-has-conversation');const c=chats.get(uid);if(!c)return;row.classList.add('chama-has-conversation');const side=document.createElement('div');side.className='chama-conversation-side';if(c.unread>0){row.classList.add('has-unread');const b=document.createElement('span');b.className='chama-unread-badge';b.textContent=c.unread>99?'99+':String(c.unread);b.title=c.unread===1?'1 mensagem não lida':`${c.unread} mensagens não lidas`;side.appendChild(b)}if(c.lastMessage){const p=document.createElement('span');p.className='chama-last-message';p.textContent=c.lastMessage.length>28?c.lastMessage.slice(0,28)+'…':c.lastMessage;side.appendChild(p)}if(side.childNodes.length)row.appendChild(side)})}
  async function start(){style();try{const appMod=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js');const app=appMod.getApps()[0];if(!app)return;const authMod=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js');fs=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js');const auth=authMod.getAuth(app);authMod.onAuthStateChanged(auth,user=>{if(stopChats){stopChats();stopChats=null}chats.clear();meUid=user?.uid||'';if(!user)return;db=fs.getFirestore(app);stopChats=fs.onSnapshot(fs.query(fs.collection(db,'chats'),fs.where('participants','array-contains',meUid)),snap=>{chats.clear();snap.forEach(d=>{const x=d.data()||{},parts=Array.isArray(x.participants)?x.participants:[],other=parts.find(v=>v&&v!==meUid);if(!other)return;const n=Number(x.unreadCounts?.[meUid]||0);chats.set(other,{unread:Number.isFinite(n)&&n>0?Math.floor(n):0,lastMessage:String(x.lastMessage||'')})});render()})})}catch(e){console.warn('Chama: badges não iniciaram',e)}const list=document.getElementById('usersList');if(list)new MutationObserver(()=>render()).observe(list,{childList:true,subtree:true})}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();
})();
