(()=>{
 const MEDIA_PREFIX='__CHAMA_MEDIA__';
 const RE=/(https?:\/\/[^\s<]+)/gi;
 const css=`.ch-video-embed{margin-top:8px;border-radius:12px;overflow:hidden;background:#000;max-width:100%}.ch-video-embed iframe,.ch-video-embed video{display:block;width:100%;aspect-ratio:16/9;border:0;background:#000}.ch-video-note{margin-top:7px;padding:9px 10px;border-radius:10px;background:#eef3f0;color:#315345;font-size:12px;line-height:1.35}.ch-video-note a{font-weight:800;color:inherit}`;
 const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
 function youtube(u){try{const x=new URL(u),h=x.hostname.replace(/^www\./,'');let id='';if(h==='youtu.be')id=x.pathname.split('/')[1]||'';else if(h.endsWith('youtube.com')){if(x.pathname==='/watch')id=x.searchParams.get('v')||'';else{const p=x.pathname.split('/').filter(Boolean);if(['shorts','embed','live'].includes(p[0]))id=p[1]||''}}return /^[\w-]{6,20}$/.test(id)?`https://www.youtube.com/embed/${id}`:null}catch{return null}}
 function tiktok(u){try{const x=new URL(u),h=x.hostname.replace(/^www\./,'');if(!h.endsWith('tiktok.com'))return null;const m=x.pathname.match(/\/video\/(\d+)/);return m?`https://www.tiktok.com/player/v1/${m[1]}?autoplay=0`:null}catch{return null}}
 function facebook(u){try{const x=new URL(u),h=x.hostname.replace(/^www\./,'');if(!(h==='facebook.com'||h==='fb.watch'||h.endsWith('.facebook.com')))return null;return `https://www.facebook.com/plugins/video.php?href=${encodeURIComponent(u)}&show_text=false&width=560`}catch{return null}}
 function directVideo(u){try{const x=new URL(u);return /\.(mp4|webm|ogg)(?:$|\?)/i.test(x.pathname+x.search)?u:null}catch{return null}}
 function shopee(u){try{const x=new URL(u),h=x.hostname.replace(/^www\./,'');return h==='shopee.com.br'||h.endsWith('.shopee.com.br')||h==='s.shopee.com.br'}catch{return false}}
 function addEmbed(bubble,url){if(bubble.querySelector(`.ch-video-embed[data-url="${CSS.escape(url)}"]`))return;const src=youtube(url)||tiktok(url)||facebook(url);const direct=directVideo(url);if(src){const wrap=document.createElement('div');wrap.className='ch-video-embed';wrap.dataset.url=url;const f=document.createElement('iframe');f.src=src;f.loading='lazy';f.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';f.allowFullscreen=true;f.referrerPolicy='strict-origin-when-cross-origin';wrap.appendChild(f);bubble.appendChild(wrap);return}if(direct){const wrap=document.createElement('div');wrap.className='ch-video-embed';wrap.dataset.url=url;const v=document.createElement('video');v.src=direct;v.controls=true;v.preload='metadata';v.playsInline=true;wrap.appendChild(v);bubble.appendChild(wrap);return}if(shopee(url)){const n=document.createElement('div');n.className='ch-video-note';n.dataset.url=url;n.innerHTML='🛍️ Link da Shopee recebido. A Shopee pode bloquear reprodução incorporada; <a target="_blank" rel="noopener noreferrer">abrir na Shopee</a>.';n.querySelector('a').href=url;bubble.appendChild(n)}}
 function process(b){if(!b||b.dataset.videoReady==='1')return;const raw=(b.textContent||'').trim();if(!raw||raw.startsWith(MEDIA_PREFIX))return;const urls=raw.match(RE)||[];[...new Set(urls)].slice(0,3).forEach(u=>addEmbed(b,u.replace(/[.,!?;:)]+$/,'')));b.dataset.videoReady='1'}
 let scheduled=false;function scan(){scheduled=false;document.querySelectorAll('#messages .bubble').forEach(process)}function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(scan)}function start(){scan();const m=document.getElementById('messages');if(m)new MutationObserver(schedule).observe(m,{childList:true,subtree:true})}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
})();
