import{getApps,getApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import{getFirestore,doc,getDoc,setDoc,updateDoc,collection,addDoc,query,where,getDocs,onSnapshot,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const app=getApps().length?getApp():null;
if(app){
const auth=getAuth(app),db=getFirestore(app);let me=null,current=null,stopIncoming=null,timer=null;
const norm=v=>String(v||"").trim().toLowerCase();
const rtc={iceServers:[{urls:["stun:stun.l.google.com:19302","stun:stun1.l.google.com:19302"]}]};
function css(){if(document.getElementById("callStyle"))return;const s=document.createElement("style");s.id="callStyle";s.textContent=`.call-btn{border:0;background:#e6f5ee;color:#0b7a53;width:42px;height:42px;border-radius:50%;font-size:19px;display:grid;place-items:center;cursor:pointer;flex:0 0 42px}.call-screen{position:fixed;inset:0;background:linear-gradient(160deg,#0b7a53,#064d37);z-index:500;display:flex;align-items:center;justify-content:center;padding:20px;color:#fff}.call-card{text-align:center;width:min(380px,100%)}.call-avatar{width:104px;height:104px;border-radius:50%;margin:0 auto 18px;background:#ffffff22;border:3px solid #ffffff55;display:grid;place-items:center;font-size:40px;font-weight:900;overflow:hidden}.call-avatar img{width:100%;height:100%;object-fit:cover}.call-name{font-size:26px;font-weight:900}.call-status{margin-top:8px;color:#d8eee5;min-height:24px}.call-time{font-size:16px;font-weight:800;margin-top:6px}.call-actions{display:flex;justify-content:center;gap:28px;margin-top:34px}.call-action{width:68px;height:68px;border:0;border-radius:50%;font-size:25px;color:#fff;display:grid;place-items:center}.call-end{background:#d92d20}.call-accept{background:#12a66a}.call-label{display:block;font-size:12px;margin-top:8px;color:#eaf7f1}.call-action-wrap{text-align:center}.call-muted{background:#ffffff25}.call-hidden{display:none!important}`;document.head.appendChild(s)}
function initials(name){return String(name||"U").trim().charAt(0).toUpperCase()||"U"}
function screen(name,status,incoming=false,photo=""){document.getElementById("callScreen")?.remove();const d=document.createElement("div");d.id="callScreen";d.className="call-screen";d.innerHTML=`<div class="call-card"><div class="call-avatar">${photo?`<img src="${photo}" alt="">`:initials(name)}</div><div class="call-name">${String(name||"Usuário").replace(/[&<>]/g,"")}</div><div id="callStatus" class="call-status">${status}</div><div id="callTime" class="call-time"></div><div class="call-actions">${incoming?`<div class="call-action-wrap"><button id="callDecline" class="call-action call-end">✕</button><span class="call-label">Recusar</span></div><div class="call-action-wrap"><button id="callAccept" class="call-action call-accept">📞</button><span class="call-label">Atender</span></div>`:`<div class="call-action-wrap"><button id="callMute" class="call-action call-muted">🎙️</button><span class="call-label">Microfone</span></div><div class="call-action-wrap"><button id="callEnd" class="call-action call-end">✕</button><span class="call-label">Encerrar</span></div>`}</div></div>`;document.body.appendChild(d);return d}
function setStatus(t){const e=document.getElementById("callStatus");if(e)e.textContent=t}
function startTimer(){let sec=0;clearInterval(timer);timer=setInterval(()=>{sec++;const m=Math.floor(sec/60),s=sec%60;const e=document.getElementById("callTime");if(e)e.textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`},1000)}
function cleanup(remove=true){clearInterval(timer);timer=null;if(current){current.unsubs?.forEach(f=>{try{f()}catch{}});current.pc?.close();current.stream?.getTracks().forEach(t=>t.stop());current.remote?.pause();current=null}if(remove)document.getElementById("callScreen")?.remove()}
async function userByEmail(email){const s=await getDocs(query(collection(db,"users"),where("email","==",norm(email))));let out=null;s.forEach(d=>{if(!out)out={uid:d.id,...d.data()}});return out}
async function preparePeer(callId,role){const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:false}),pc=new RTCPeerConnection(rtc),remote=document.createElement("audio");remote.autoplay=true;remote.playsInline=true;document.body.appendChild(remote);stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{remote.srcObject=e.streams[0];remote.play().catch(()=>{})};pc.onconnectionstatechange=()=>{if(pc.connectionState==="connected"){setStatus("Em ligação");startTimer()}if(["failed","disconnected","closed"].includes(pc.connectionState)&&current)setStatus("Ligação encerrada")};const mine=role==="caller"?"callerCandidates":"calleeCandidates";pc.onicecandidate=e=>{if(e.candidate)addDoc(collection(db,"calls",callId,mine),e.candidate.toJSON()).catch(()=>{})};return{pc,stream,remote}}
async function startCall(){if(current||!me)return;const email=document.getElementById("chatEmail")?.textContent||"";if(!email)return alert("Abra uma conversa antes de ligar.");let target;try{target=await userByEmail(email)}catch{}if(!target)return alert("Não consegui localizar esse usuário.");const name=target.nome||document.getElementById("chatName")?.textContent||"Usuário";screen(name,"Chamando...",false,target.foto||"");try{const ref=doc(collection(db,"calls")),media=await preparePeer(ref.id,"caller"),offer=await media.pc.createOffer();await media.pc.setLocalDescription(offer);await setDoc(ref,{callerId:me.uid,callerName:auth.currentUser?.displayName||"Usuário",calleeId:target.uid,calleeName:name,status:"ringing",offer:{type:offer.type,sdp:offer.sdp},createdAt:serverTimestamp()});current={id:ref.id,ref,role:"caller",...media,unsubs:[]};const stopCall=onSnapshot(ref,async s=>{if(!s.exists())return;const d=s.data();if(d.answer&&!current.pc.currentRemoteDescription){await current.pc.setRemoteDescription(new RTCSessionDescription(d.answer))}if(d.status==="active")setStatus("Conectando...");if(["declined","ended","missed"].includes(d.status)){setStatus(d.status==="declined"?"Ligação recusada":"Ligação encerrada");setTimeout(()=>cleanup(),900)}});const stopIce=onSnapshot(collection(db,"calls",ref.id,"calleeCandidates"),s=>s.docChanges().forEach(c=>{if(c.type==="added")current?.pc?.addIceCandidate(new RTCIceCandidate(c.doc.data())).catch(()=>{})}));current.unsubs.push(stopCall,stopIce);const end=document.getElementById("callEnd");if(end)end.onclick=()=>endCall();const mute=document.getElementById("callMute");if(mute)mute.onclick=()=>{const t=current?.stream?.getAudioTracks()[0];if(!t)return;t.enabled=!t.enabled;mute.textContent=t.enabled?"🎙️":"🔇"}}catch(e){cleanup();alert(e?.name==="NotAllowedError"?"Permita o uso do microfone para fazer a ligação.":"Não consegui iniciar a ligação.")}}
async function acceptCall(c){if(current)return;const d=c.data;const ui=screen(d.callerName||"Usuário","Conectando...",false,d.callerPhoto||"");try{const media=await preparePeer(c.id,"callee");current={id:c.id,ref:doc(db,"calls",c.id),role:"callee",...media,unsubs:[]};await media.pc.setRemoteDescription(new RTCSessionDescription(d.offer));const answer=await media.pc.createAnswer();await media.pc.setLocalDescription(answer);await updateDoc(current.ref,{answer:{type:answer.type,sdp:answer.sdp},status:"active",answeredAt:serverTimestamp()});const stopIce=onSnapshot(collection(db,"calls",c.id,"callerCandidates"),s=>s.docChanges().forEach(ch=>{if(ch.type==="added")current?.pc?.addIceCandidate(new RTCIceCandidate(ch.doc.data())).catch(()=>{})}));const stopCall=onSnapshot(current.ref,s=>{const x=s.data();if(x?.status==="ended"){setStatus("Ligação encerrada");setTimeout(()=>cleanup(),700)}});current.unsubs.push(stopIce,stopCall);ui.querySelector("#callEnd")?.addEventListener("click",endCall);const mute=ui.querySelector("#callMute");if(mute)mute.onclick=()=>{const t=current?.stream?.getAudioTracks()[0];if(!t)return;t.enabled=!t.enabled;mute.textContent=t.enabled?"🎙️":"🔇"}}catch(e){try{await updateDoc(doc(db,"calls",c.id),{status:"ended",endedAt:serverTimestamp()})}catch{}cleanup();alert(e?.name==="NotAllowedError"?"Permita o uso do microfone para atender.":"Não consegui atender a ligação.")}}
async function endCall(){const ref=current?.ref;try{if(ref)await updateDoc(ref,{status:"ended",endedAt:serverTimestamp()})}catch{}cleanup()}
function incoming(c){if(current||document.getElementById("callScreen"))return;const d=c.data,ui=screen(d.callerName||"Usuário","Ligação de voz recebida",true,d.callerPhoto||"");ui.querySelector("#callAccept").onclick=()=>acceptCall(c);ui.querySelector("#callDecline").onclick=async()=>{try{await updateDoc(doc(db,"calls",c.id),{status:"declined",endedAt:serverTimestamp()})}catch{}ui.remove()}}
function listenIncoming(){stopIncoming?.();if(!me)return;stopIncoming=onSnapshot(query(collection(db,"calls"),where("calleeId","==",me.uid)),s=>s.docChanges().forEach(ch=>{if(ch.type!=="removed"){const d=ch.doc.data();if(d.status==="ringing")incoming({id:ch.doc.id,data:d})}}))}
function installButton(){const head=document.querySelector("#activeChat .chat-head");if(!head||document.getElementById("voiceCallBtn"))return;const b=document.createElement("button");b.id="voiceCallBtn";b.className="call-btn";b.type="button";b.title="Ligação de voz";b.textContent="📞";b.onclick=startCall;const cat=document.getElementById("chatCatalogBtn");head.insertBefore(b,cat||null)}
function start(){css();document.addEventListener("click",()=>setTimeout(installButton,80),true);onAuthStateChanged(auth,u=>{me=u||null;cleanup();document.getElementById("voiceCallBtn")?.remove();stopIncoming?.();stopIncoming=null;if(u){installButton();listenIncoming()}})}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",start):start();
}