const enc=new TextEncoder();
const b64u=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const json64=o=>b64u(enc.encode(JSON.stringify(o)));
function pemBytes(pem){const clean=String(pem||'').replace(/\\n/g,'\n').replace(/-----BEGIN PRIVATE KEY-----/,'').replace(/-----END PRIVATE KEY-----/,'').replace(/\s+/g,'');const bin=atob(clean);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
async function serviceToken(env){const now=Math.floor(Date.now()/1000),head=json64({alg:'RS256',typ:'JWT'}),body=json64({iss:env.FIREBASE_CLIENT_EMAIL,scope:'https://www.googleapis.com/auth/firebase.messaging',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600});const key=await crypto.subtle.importKey('pkcs8',pemBytes(env.FIREBASE_PRIVATE_KEY),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,enc.encode(head+'.'+body));const assertion=head+'.'+body+'.'+b64u(sig);const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})});if(!r.ok)throw new Error('oauth '+r.status+' '+await r.text());return(await r.json()).access_token}
function field(v){if(!v)return null;if('stringValue'in v)return v.stringValue;if('arrayValue'in v)return(v.arrayValue.values||[]).map(field);return null}
async function fg(project,path,idToken){const r=await fetch(`https://firestore.googleapis.com/v1/projects/${project}/databases/(default)/documents/${path}`,{headers:{authorization:'Bearer '+idToken}});if(!r.ok)throw new Error('firestore '+r.status+' '+await r.text());return r.json()}
export async function onRequestPost({request,env}){try{const a=request.headers.get('authorization')||'';if(!a.startsWith('Bearer '))return new Response('unauthorized',{status:401});const idToken=a.slice(7),b=await request.json(),channelId=String(b.channelId||''),postId=String(b.postId||'');if(!channelId||!postId)return new Response('bad request',{status:400});const project=env.FIREBASE_PROJECT_ID||'chama-cfc28';const [channel,post]=await Promise.all([fg(project,'channels/'+encodeURIComponent(channelId),idToken),fg(project,'channels/'+encodeURIComponent(channelId)+'/posts/'+encodeURIComponent(postId),idToken)]);const ownerId=field(channel.fields?.ownerId),postOwner=field(post.fields?.ownerId);if(!ownerId||postOwner!==ownerId)return new Response('forbidden',{status:403});const followers=(field(channel.fields?.followers)||[]).filter(x=>x&&x!==ownerId).slice(0,200);if(!followers.length)return Response.json({sent:0,reason:'no_followers'});if(!env.FIREBASE_CLIENT_EMAIL||!env.FIREBASE_PRIVATE_KEY)return Response.json({sent:0,reason:'server_not_configured'},{status:503});const access=await serviceToken(env),origin=new URL(request.url).origin,name=String(field(channel.fields?.name)||'Canal Chama').slice(0,80),text=String(field(post.fields?.text)||'Nova publicação').slice(0,120),link=origin+'/?channel='+encodeURIComponent(channelId);let sent=0,total=0;for(const uid of followers){let u;try{u=await fg(project,'users/'+encodeURIComponent(uid),idToken)}catch{continue}const primary=field(u.fields?.pushToken),list=field(u.fields?.pushTokens)||[],tokens=[...new Set([primary,...(Array.isArray(list)?list:[])].filter(Boolean))].slice(0,3);for(const token of tokens){total++;const payload={message:{token,data:{type:'chama_channel',channelId,postId,channelName:name,text},webpush:{headers:{Urgency:'normal',TTL:'1800'},notification:{title:'📢 '+name,body:text,icon:origin+'/icon.svg',badge:origin+'/icon.svg',tag:'chama-channel-'+channelId,renotify:true,vibrate:[180,100,180],data:{type:'chama_channel',channelId}},fcm_options:{link}}}};const r=await fetch(`https://fcm.googleapis.com/v1/projects/${project}/messages:send`,{method:'POST',headers:{authorization:'Bearer '+access,'content-type':'application/json'},body:JSON.stringify(payload)});if(r.ok)sent++}}
return Response.json({sent,total})}catch(e){console.error('channel push',e);return Response.json({sent:0,reason:e?.message||'erro'},{status:500})}}
